import { Check, Clock, RefreshCcw, ScanSearch, Sparkles, Upload } from 'lucide-react'
import { getAsrRuntimeStatusMessage } from './app-helpers'
import { useAppContext } from './app-context'

export function AsrRuntimeCard(): React.ReactElement {
  const app = useAppContext()
  const status = app.asrStatus
  const runtimeReady = Boolean(status?.binaryPath && status?.ffmpegPath)
  return <div className="asr-card open"><div className="asr-card-heading"><div className="asr-card-title"><Sparkles size={18} /><span>{app.copy.asrPanel.engineStatus}</span></div><button className="mini-tool-button" type="button" onClick={() => void app.refreshAsrStatus()} title={app.copy.asrPanel.refreshEngine}><RefreshCcw size={14} /></button></div><p>{getAsrRuntimeStatusMessage(app.copy, status)}</p><div className="asr-meta"><span><Clock size={14} />{app.installedModelCount} {app.copy.asrPanel.modelFiles}</span><span>{runtimeReady ? app.copy.asrPanel.engineReady : app.copy.asrPanel.engineNotReady}</span></div><div className="asr-runtime-grid"><span>{app.copy.asrPanel.engineStatus}</span><strong>{status?.binaryPath ? app.copy.asrPanel.engineReady : app.copy.asrPanel.engineNotReady}</strong><span>ffmpeg</span><strong>{status?.ffmpegPath ? app.copy.asrPanel.engineReady : app.copy.asrPanel.engineNotReady}</strong></div>{status && !runtimeReady ? <div className="asr-action-row"><button className="asr-action-button primary" type="button" onClick={() => void app.autoDetectWhisperBinary()} disabled={app.isDetectingWhisperBinary || app.isSelectingWhisperBinary}><ScanSearch size={15} />{app.isDetectingWhisperBinary ? app.copy.asrPanel.detectingEngine : app.copy.runtimeDialog.autoDetectTitle}</button><button className="asr-action-button" type="button" onClick={() => void app.selectWhisperBinary()} disabled={app.isDetectingWhisperBinary || app.isSelectingWhisperBinary}><Upload size={15} />{app.copy.runtimeDialog.selectWhisperTitle}</button></div> : runtimeReady ? <div className="asr-runtime-ready"><Check size={14} />{app.copy.asrPanel.engineReady}</div> : null}{app.runtimeSetupMessage ? <div className={`asr-result ${app.runtimeSetupMessage.success ? 'success' : 'failed'}`}>{app.runtimeSetupMessage.message}</div> : null}</div>
}
