import { Bookmark, BookmarkPlus, ChevronDown, Fullscreen, Minimize2, Pause, Play, Repeat, Repeat1, Shuffle, SkipBack, SkipForward, Square, Volume2, VolumeX } from 'lucide-react'
import { formatTime } from '../lib/time'
import { getPlaybackMediaKey } from '../../../shared/playback-memory'
import { QuickSubtitleButton } from './quick-subtitle-button'
import { useAppContext } from './app-context'

function PlaybackPrimaryControls(): React.ReactElement {
  const app = useAppContext()
  const { state, copy } = app
  return <div className="controls-primary"><div className="control-group transport-group"><button className="round-button" type="button" onClick={() => app.playAdjacent(-1)} title={copy.controls.previous}><SkipBack size={16} /></button><button className="round-button primary" type="button" onClick={app.togglePlay} title={`${state.isPlaying ? copy.controls.pause : copy.controls.play} (Space)`} aria-keyshortcuts="Space">{state.isPlaying ? <Pause size={18} /> : <Play size={18} />}</button><button className="round-button" type="button" onClick={() => app.playAdjacent(1)} title={copy.controls.next}><SkipForward size={16} /></button></div><button className="round-button stop-button" type="button" onClick={app.stopPlayback} title={`${copy.controls.stopAndReset} (S)`} aria-label={copy.controls.stopAndReset} aria-keyshortcuts="S"><Square size={14} fill="currentColor" stroke="none" /><span>{copy.controls.stop}</span></button><div className="control-group volume-group"><button className="round-button" type="button" onClick={app.toggleMute} title={copy.controls.mute}>{state.muted ? <VolumeX size={16} /> : <Volume2 size={16} />}</button><input className="volume" type="range" min="0" max="1" step="0.01" value={state.muted ? 0 : state.volume} onChange={(event) => { const volume = Number(event.currentTarget.value); const muted = volume === 0; if (app.videoRef.current) { app.videoRef.current.volume = volume; app.videoRef.current.muted = muted }; app.setState((current) => ({ ...current, volume, muted })); app.syncPlaybackMemory(volume, muted, state.playbackRate) }} aria-label={copy.controls.volume} /></div></div>
}

function PlaybackModeControls(): React.ReactElement {
  const app = useAppContext()
  const { copy } = app
  const repeatTitle = app.appSettings.playback.repeatMode === 'current' ? copy.controls.repeatCurrent : app.appSettings.playback.repeatMode === 'all' ? copy.controls.repeatAll : copy.controls.repeatNone
  const endActionTitle = app.appSettings.playback.endAction === 'next' ? copy.controls.endActionNext : copy.controls.endActionStop
  return <div className="control-group playback-mode-group"><button className={`round-button mode-button ${app.appSettings.playback.repeatMode !== 'none' ? 'active' : ''}`} type="button" onClick={app.cycleRepeatMode} title={`${copy.controls.repeat}: ${repeatTitle}`} aria-label={`${copy.controls.repeat}: ${repeatTitle}`} aria-pressed={app.appSettings.playback.repeatMode !== 'none'}>{app.appSettings.playback.repeatMode === 'current' ? <Repeat1 size={16} /> : <Repeat size={16} />}</button><button className={`round-button mode-button ${app.appSettings.playback.order === 'shuffle' ? 'active' : ''}`} type="button" onClick={app.togglePlaybackOrder} title={app.appSettings.playback.order === 'shuffle' ? copy.controls.shuffleOn : copy.controls.shuffleOff} aria-label={copy.controls.shuffle} aria-pressed={app.appSettings.playback.order === 'shuffle'}><Shuffle size={16} /></button><button className="round-button mode-button" type="button" onClick={app.togglePlaybackEndAction} title={endActionTitle} aria-label={endActionTitle} aria-pressed={app.appSettings.playback.endAction === 'next'}>{app.appSettings.playback.endAction === 'next' ? <SkipForward size={16} /> : <Square size={13} fill="currentColor" stroke="none" />}</button></div>
}

function PlaybackSecondaryControls(): React.ReactElement {
  const app = useAppContext()
  const { state, copy } = app
  return <div className="control-group secondary-group"><div className="speed-control"><select className="speed-select" value={state.playbackRate} onChange={(event) => { const playbackRate = Number(event.currentTarget.value); if (app.videoRef.current) app.videoRef.current.playbackRate = playbackRate; app.setState((current) => ({ ...current, playbackRate })); app.syncPlaybackMemory(state.volume, state.muted, playbackRate) }} aria-label={copy.controls.playbackSpeed}>{[0.5, 0.75, 1, 1.25, 1.5, 2].map((speed) => <option key={speed} value={speed}>{speed}x</option>)}</select><ChevronDown className="speed-control-icon" size={12} aria-hidden="true" /></div><PlaybackModeControls /><button className="round-button" type="button" onClick={() => app.createPlaybackBookmark(copy.controls.bookmarkAt(formatTime(state.currentTime)))} title={copy.controls.addBookmark} aria-label={copy.controls.addBookmark}><BookmarkPlus size={16} /></button><button className="round-button" type="button" onClick={() => void app.toggleFullscreen()} title={app.isFullscreen ? copy.controls.exitFullscreen : copy.controls.fullscreen} aria-label={app.isFullscreen ? copy.controls.exitFullscreen : copy.controls.fullscreen} aria-pressed={app.isFullscreen} aria-keyshortcuts="F">{app.isFullscreen ? <Minimize2 size={16} /> : <Fullscreen size={16} />}</button></div>
}

export function PlaybackControls(): React.ReactElement | null {
  const app = useAppContext()
  if (!app.hasCurrentFile) return null
  const { state, copy } = app
  const duration = state.duration || app.mediaMetadata?.durationSeconds || 0
  const fileKey = state.currentFile ? getPlaybackMediaKey(state.currentFile) : null
  const bookmarks = fileKey ? app.appSettings.playback.bookmarksByFingerprint[fileKey] ?? [] : []
  const chapters = app.mediaMetadata?.chapters ?? []
  const markerPercent = (timeSeconds: number): number => duration > 0 ? Math.min(100, Math.max(0, timeSeconds / duration * 100)) : 0
  return <div className={`control-deck ${app.isControlDeckHidden ? 'is-hidden' : ''}`} aria-hidden={app.isControlDeckHidden}><div className="timeline-row"><span>{formatTime(state.currentTime)}</span><div className="timeline-shell"><div className="timeline-markers">{chapters.map((chapter) => <button className="timeline-marker chapter-marker" key={`chapter-${chapter.id}-${chapter.startSeconds}`} type="button" style={{ left: `${markerPercent(chapter.startSeconds)}%` }} title={copy.controls.chapterAt(chapter.title, formatTime(chapter.startSeconds))} aria-label={copy.controls.chapterAt(chapter.title, formatTime(chapter.startSeconds))} onClick={() => app.seekTo(chapter.startSeconds)}><span /></button>)}{bookmarks.map((bookmark) => <button className="timeline-marker bookmark-marker" key={bookmark.id} type="button" style={{ left: `${markerPercent(bookmark.timeSeconds)}%` }} title={`${bookmark.name} · ${formatTime(bookmark.timeSeconds)} · ${copy.controls.removeBookmark}`} aria-label={`${bookmark.name} · ${formatTime(bookmark.timeSeconds)}`} onClick={() => app.seekTo(bookmark.timeSeconds)} onContextMenu={(event) => { event.preventDefault(); app.removePlaybackBookmark(bookmark.id) }}><Bookmark size={10} /></button>)}</div><input className="timeline" type="range" min="0" max={duration} value={state.currentTime} step="0.1" onChange={(event) => { const currentTime = Number(event.currentTarget.value); if (app.videoRef.current) app.videoRef.current.currentTime = currentTime; app.setState((current) => ({ ...current, currentTime })) }} aria-label={copy.controls.playbackPosition} /></div><span>{app.playbackTimeLabel}</span></div><div className="controls-row"><div className="controls-center-group"><PlaybackPrimaryControls /><PlaybackSecondaryControls /></div><div className="quick-subtitle-action"><QuickSubtitleButton /></div></div></div>
}
