import type { MouseEvent } from 'react'
import { ChevronDown, Copy, Download, FileText, FolderOpen, ListVideo } from 'lucide-react'
import { useAppContext } from './app-context'

export function SubtitleActionsMenu(): React.ReactElement | null {
  const app = useAppContext()
  if (!app.canOpenSubtitleTools) return null
  const close = (event: MouseEvent<HTMLButtonElement>): void => event.currentTarget.closest('details')?.removeAttribute('open')
  const action = (event: MouseEvent<HTMLButtonElement>, handler: () => void): void => { close(event); handler() }
  return <details ref={app.subtitleActionsRef} className="subtitle-actions"><summary className="subtitle-actions-summary" title={app.copy.asrPanel.subtitleTools} aria-label={app.copy.asrPanel.subtitleTools}><ChevronDown size={12} />{app.copy.asrPanel.subtitleTools}</summary><div className="subtitle-actions-menu" role="menu" aria-label={app.copy.asrPanel.subtitleToolsMenu}><button className="subtitle-action-item" type="button" role="menuitem" onClick={(event) => action(event, app.openClipExportDialog)} disabled={app.isExportingClip}><ListVideo size={14} />{app.copy.asrPanel.clipExport}</button>{app.canOpenSubtitleFolder ? <button className="subtitle-action-item" type="button" role="menuitem" onClick={(event) => action(event, () => void app.openSubtitleFolder())}><FolderOpen size={14} />{app.copy.asrPanel.openSubtitleFolder}</button> : null}{app.canOpenSubtitleSrt ? <button className="subtitle-action-item" type="button" role="menuitem" onClick={(event) => action(event, () => void app.openSubtitleSrtFile())}><FileText size={14} />{app.copy.asrPanel.openSrtFile}</button> : null}{app.canOpenTranslatedSubtitleSrt ? <button className="subtitle-action-item" type="button" role="menuitem" onClick={(event) => action(event, () => void app.openTranslatedSubtitleSrtFile())}><FileText size={14} />{app.copy.asrPanel.openTranslatedSrtFile}</button> : null}<PathAction label={app.copy.asrPanel.copySrtPath} icon={<Copy size={14} />} enabled={app.canOpenSubtitleSrt} onClick={(event) => action(event, () => void app.copySubtitleSrtPath())} /><PathAction label={app.copy.asrPanel.copyTranslatedSrtPath} icon={<Copy size={14} />} enabled={app.canOpenTranslatedSubtitleSrt} onClick={(event) => action(event, () => void app.copyTranslatedSubtitleSrtPath())} /><PathAction label={app.copy.asrPanel.copyVttPath} icon={<Copy size={14} />} enabled={app.canOpenSubtitleFolder} onClick={(event) => action(event, () => void app.copySubtitleVttPath())} /><PathAction label={app.copy.asrPanel.copyTranslatedVttPath} icon={<Copy size={14} />} enabled={Boolean(app.translatedSubtitlePath)} onClick={(event) => action(event, () => void app.copyTranslatedSubtitleVttPath())} />{app.canOpenSubtitleFolder ? <button className="subtitle-action-item" type="button" role="menuitem" onClick={(event) => action(event, () => void app.exportSubtitleSrtFile())}><Download size={14} />{app.copy.asrPanel.exportSrt}</button> : null}</div></details>
}

function PathAction(props: { label: string; icon: React.ReactElement; enabled: boolean; onClick: (event: MouseEvent<HTMLButtonElement>) => void }): React.ReactElement | null {
  if (!props.enabled) return null
  return <button className="subtitle-action-item" type="button" role="menuitem" onClick={props.onClick}>{props.icon}{props.label}</button>
}
