import { describe, expect, it } from 'vitest'
import { readSource } from './test-source-utils'

describe('stateful control source contracts', () => {
  it('keeps playback control labels and actions derived from shared contracts', () => {
    const playbackControls = readSource('src/renderer/src/app/playback-controls.tsx')
    const playbackActions = readSource('src/renderer/src/app/use-playback-controls.ts')
    const editingAudio = readSource('src/renderer/src/app/editing-audio-control.tsx')
    const editingTransition = readSource('src/renderer/src/app/editing-transition-control.tsx')
    const editingMotion = readSource('src/renderer/src/app/editing-clip-motion-control.tsx')
    const editingTimeline = readSource('src/renderer/src/app/editing-timeline.tsx')
    const editingActions = readSource('src/renderer/src/app/use-editing-actions.ts')
    const clipPreview = readSource('src/renderer/src/app/clip-editor-preview.tsx')
    const imageControls = readSource('src/renderer/src/app/image-editor-controls.tsx')
    const personMatte = readSource('src/renderer/src/app/editing-person-matte-control.tsx')
    const batchJob = readSource('src/renderer/src/app/batch-panel-job.tsx')

    expect(playbackControls).toContain('getTransportAction(state.isPlaying)')
    expect(playbackControls).toContain('getMuteAction(state.muted)')
    expect(playbackControls).toContain('aria-label={muteLabel}')
    expect(playbackControls).toContain("getShuffleAction(shuffleEnabled) === 'disable'")
    expect(playbackControls).not.toContain('copy.controls.shuffleOff : copy.controls.shuffleOn')
    expect(playbackControls).toContain('const fullscreenState = getFullscreenControlState(document.fullscreenElement, app.fullscreenRef.current)')
    expect(playbackControls).toContain('aria-pressed={fullscreenState.isActive}')
    expect(playbackActions).toContain('const fullscreenState = getFullscreenControlState(document.fullscreenElement, fullscreenTarget)')
    expect(playbackActions).toContain("if (getTransportAction(isMediaPlaying(video)) === 'pause')")
    expect(playbackActions).toContain("const muted = getMuteAction(video.muted) === 'mute'")
    expect(playbackActions).toContain("getShuffleAction(current.order === 'shuffle')")
    expect(playbackActions).toContain("if (fullscreenState.action === 'exit') await document.exitFullscreen()")
    expect(playbackActions).toContain('else if (fullscreenTarget) await fullscreenTarget.requestFullscreen()')
    expect(editingAudio).toContain('const audioActionLabel = muted ? unmuteLabel : muteLabel')
    expect(editingAudio).toContain('aria-pressed={muted}')
    expect(editingTransition).toContain('aria-pressed={!active}')
    expect(editingTransition).toContain('aria-pressed={active && value.type === type}')
    expect(editingMotion).toContain('aria-pressed={motion.enterMotion === value}')
    expect(editingMotion).toContain('aria-pressed={motion.exitMotion === value}')
    expect(editingTimeline).toContain('const editingTransportAction = getTransportAction(app.state.isPlaying)')
    expect(editingTimeline).toContain("aria-pressed={editingTransportAction === 'pause'}")
    expect(editingActions).toContain("if (getTransportAction(isMediaPlaying(video)) === 'pause')")
    expect(clipPreview).toContain('aria-pressed={isPlaying}')
    expect(imageControls).toContain('aria-pressed={settings.flipX}')
    expect(imageControls).toContain('aria-pressed={settings.lockAspectRatio}')
    expect(personMatte).toContain('getToggleAction(settings.enabled)')
    expect(personMatte).toContain('aria-pressed={settings.enabled}')
    expect(batchJob).toContain('aria-pressed={job.status === \'paused\'}')
  })

  it('keeps top-level toggle labels and icons aligned with their current state', () => {
    const header = readSource('src/renderer/src/app/app-header.tsx')

    expect(header).toContain('isMaximized ? <Minimize2')
    expect(header).toContain(': <Maximize2')
    expect(header).toContain('aria-pressed={isMaximized}')
    expect(header).toContain('const toggleImageWorkspace = (): void =>')
    expect(header).toContain("current === 'image' ? 'video' : 'image'")
    expect(header).toContain('aria-pressed={app.viewMode === \'image\'}')
  })
})
