import { describe, expect, it } from 'vitest'
import { readSource } from './test-source-utils'

describe('editing timeline source contracts', () => {
  it('renders the editing rail from the player stage and exposes core edit actions', () => {
    const stage = readSource('src/renderer/src/app/player-stage.tsx')
    const timeline = readSource('src/renderer/src/app/editing-timeline.tsx')
    const actions = readSource('src/renderer/src/app/use-editing-actions.ts')
    const actionHelpers = readSource('src/renderer/src/app/editing-action-helpers.ts')
    const storage = readSource('src/renderer/src/app/editing-project-storage.ts')
    const captionEffect = readSource('src/renderer/src/app/use-editing-caption-effect.ts')
    const captionTrack = readSource('src/renderer/src/app/editing-caption-track.tsx')
    const captionActions = readSource('src/renderer/src/app/editing-caption-actions.ts')
    const captionLoader = readSource('src/renderer/src/app/editing-caption-loader.ts')
    const exportAction = readSource('src/renderer/src/app/editing-export-action.ts')
    const audioControl = readSource('src/renderer/src/app/editing-audio-control.tsx')
    const rangeTrack = readSource('src/renderer/src/app/editing-range-track.tsx')
    const boundaryHandles = readSource('src/renderer/src/app/editing-clip-boundary-handles.tsx')
    const exportSummary = readSource('src/renderer/src/app/editing-export-summary.tsx')
    const exportConfirm = readSource('src/renderer/src/app/editing-export-confirm-dialog.tsx')
    const playbackEffect = readSource('src/renderer/src/app/use-editing-playback-effect.ts')

    expect(stage).toContain("app.isEditingMode ? <EditingTimeline /> : <PlaybackControls />")
    expect(timeline).toContain('data-testid="editing-timeline"')
    expect(timeline).toContain('data-testid="editing-track"')
    expect(timeline).toContain('app.splitEditingClip')
    expect(timeline).toContain('app.trimEditingClipLeft')
    expect(timeline).toContain('app.trimEditingClipRight')
    expect(timeline).toContain('app.deleteEditingClip')
    expect(timeline).toContain('app.exportEditingTimeline')
    expect(timeline).toContain('app.isExportingClip')
    expect(timeline).toContain('app.undoEditing')
    expect(timeline).toContain('app.redoEditing')
    expect(timeline).toContain('app.newEditingProject')
    expect(timeline).toContain('app.openEditingProjectFile')
    expect(timeline).toContain('app.saveEditingProjectFile')
    expect(timeline).toContain('app.resetEditingProject')
    expect(timeline).toContain('app.reorderEditingClips')
    expect(timeline).toContain('app.selectEditingClip')
    expect(timeline).toContain('<EditingCaptionTrack')
    expect(captionTrack).toContain('data-testid="editing-caption-track"')
    expect(captionTrack).toContain('onMoveCaption')
    expect(captionActions).toContain('moveEditingCaption')
    expect(captionEffect).toContain('sourceKey')
    expect(captionLoader).toContain('createEditingCaptionPathCandidates')
    expect(exportAction).toContain('serializeEditingCaptionsToSrt')
    expect(exportAction).toContain('subtitleText')
    expect(timeline).toContain('<EditingAudioControl')
    expect(timeline).toContain('app.setEditingClipVolume')
    expect(timeline).toContain('<EditingRangeTrack')
    expect(timeline).toContain('app.deleteEditingRange')
    expect(audioControl).toContain('editing-audio-range')
    expect(rangeTrack).toContain('setPointerCapture')
    expect(rangeTrack).toContain('deleteSelectedRange')
    expect(timeline).toContain('<EditingClipBoundaryHandles')
    expect(timeline).toContain('app.updateEditingClipBoundary')
    expect(boundaryHandles).toContain('setPointerCapture')
    expect(boundaryHandles).toContain('onCommit(span.clip.id, current.boundary, current.currentSeconds)')
    expect(timeline).toContain('<EditingExportSummary')
    expect(exportSummary).toContain('data-testid="editing-export-summary"')
    expect(exportSummary).toContain('formatResolution')
    expect(exportSummary).toContain('isEditingClipMuted')
    expect(timeline).toContain('<EditingExportConfirmDialog')
    expect(timeline).toContain('setIsExportConfirmOpen(true)')
    expect(timeline).toContain('data-testid="editing-export"')
    expect(exportConfirm).toContain('useModalFocusTrap')
    expect(exportConfirm).toContain('data-testid="editing-export-confirm"')
    expect(exportConfirm).toContain('outputFileName')
    expect(exportConfirm).toContain('chooseTimelineExportPath')
    expect(exportConfirm).toContain('outputVideoPath')
    expect(exportAction).toContain('requestedMode')
    expect(playbackEffect).toContain('applyClipAudio')
    expect(timeline).toContain('app.addEditingSources')
    expect(timeline).toContain('useEditingFilmstrip')
    expect(actions).toContain('createEditingClipActions(model)')
    expect(actions).toContain('createEditingSourceActions(model, derived)')
    expect(timeline).toContain('data-testid="editing-add-media"')
    expect(actions).toContain('useEditingPlaybackEffect(model)')
    expect(actions).toContain('seekEditingTime: (seconds: number) => seekEditingTime(model, seconds)')
    expect(actions).toContain('loadEditingProject(source)')
    expect(actionHelpers).toContain('saveEditingProject(nextProject)')
    expect(storage).toContain('aivplayer.editing-projects.v1')
    expect(captionEffect).toContain('loadEditingCaptions')
    expect(readSource('src/renderer/src/app/use-editing-playback-effect.ts')).toContain('loadedmetadata')
  })

  it('keeps the timeline stylesheet semantic and token-driven', () => {
    const playerStyles = readSource('src/renderer/src/styles/player.css')
    const shellStyles = readSource('src/renderer/src/styles/player/editing-timeline-shell.css')
    const actionStyles = readSource('src/renderer/src/styles/player/editing-timeline-actions.css')
    const trackStyles = readSource('src/renderer/src/styles/player/editing-timeline-track.css')
    const clipStyles = readSource('src/renderer/src/styles/player/editing-timeline-clips.css')
    const filmstripStyles = readSource('src/renderer/src/styles/player/editing-timeline-filmstrip.css')
    const captionStyles = readSource('src/renderer/src/styles/player/editing-timeline-captions.css')
    const audioStyles = readSource('src/renderer/src/styles/player/editing-timeline-audio.css')
    const rangeStyles = readSource('src/renderer/src/styles/player/editing-timeline-range.css')
    const boundaryStyles = readSource('src/renderer/src/styles/player/editing-timeline-boundaries.css')
    const exportSummaryStyles = readSource('src/renderer/src/styles/player/editing-timeline-export-summary.css')
    const exportTargetStyles = readSource('src/renderer/src/styles/player/editing-timeline-export-target.css')

    expect(playerStyles).toContain("@import './player/editing-timeline-shell.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-actions.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-track.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-clips.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-filmstrip.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-captions.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-audio.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-range.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-boundaries.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-export-summary.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-export-target.css';")
    expect(shellStyles + actionStyles + trackStyles + clipStyles + filmstripStyles + captionStyles + audioStyles + rangeStyles + boundaryStyles + exportSummaryStyles + exportTargetStyles).toContain('var(--bg-control)')
    expect(shellStyles + actionStyles + trackStyles + clipStyles + filmstripStyles + captionStyles + audioStyles + rangeStyles + boundaryStyles + exportSummaryStyles + exportTargetStyles).toContain('var(--accent)')
    expect(shellStyles + actionStyles + trackStyles + clipStyles + filmstripStyles + captionStyles + audioStyles + rangeStyles + boundaryStyles + exportSummaryStyles + exportTargetStyles).not.toMatch(/#[0-9a-fA-F]{3,8}/)
  })
})
