import { describe, expect, it } from 'vitest'
import { readSource } from './test-source-utils'

describe('editing timeline source contracts', () => {
  it('renders the editing rail from the player stage and exposes core edit actions', () => {
    const stage = readSource('src/renderer/src/app/player-stage.tsx')
    const timeline = readSource('src/renderer/src/app/editing-timeline.tsx')
    const actions = readSource('src/renderer/src/app/use-editing-actions.ts')
    const clipActions = readSource('src/renderer/src/app/editing-clip-actions.ts')
    const timelineSelection = readSource('src/renderer/src/app/use-editing-timeline-selection.ts')
    const actionHelpers = readSource('src/renderer/src/app/editing-action-helpers.ts')
    const storage = readSource('src/renderer/src/app/editing-project-storage.ts')
    const captionEffect = readSource('src/renderer/src/app/use-editing-caption-effect.ts')
    const captionReloadConflict = readSource('src/renderer/src/app/editing-caption-reload-conflict.tsx')
    const subtitleReloadCopy = readSource('src/shared/editing-subtitle-reload-copy.ts')
    const captionTrack = readSource('src/renderer/src/app/editing-caption-track.tsx')
    const graphicTrack = readSource('src/renderer/src/app/editing-graphic-track.tsx')
    const videoBlockTrack = readSource('src/renderer/src/app/editing-video-block-track.tsx')
    const captionActions = readSource('src/renderer/src/app/editing-caption-actions.ts')
    const captionLoader = readSource('src/renderer/src/app/editing-caption-loader.ts')
    const exportAction = readSource('src/renderer/src/app/editing-export-action.ts')
    const exportAudit = readSource('src/core/editing/export-audit.ts')
    const audioControl = readSource('src/renderer/src/app/editing-audio-control.tsx')
    const rangeTrack = readSource('src/renderer/src/app/editing-range-track.tsx')
    const boundaryHandles = readSource('src/renderer/src/app/editing-clip-boundary-handles.tsx')
    const exportSummary = readSource('src/renderer/src/app/editing-export-summary.tsx')
    const exportConfirm = readSource('src/renderer/src/app/editing-export-confirm-dialog.tsx')
    const clipExport = readSource('src/renderer/src/app/clip-export-dialog.tsx')
    const ffmpegCapabilityStatus = readSource('src/renderer/src/app/ffmpeg-capability-status.tsx')
    const playbackEffect = readSource('src/renderer/src/app/use-editing-playback-effect.ts')
    const scriptPanel = readSource('src/renderer/src/app/editing-script-panel.tsx')
    const scriptActions = readSource('src/renderer/src/app/editing-script-actions.ts')
    const scriptOperations = readSource('src/core/editing/script-operations.ts')
    const snapping = readSource('src/core/editing/timeline-snapping.ts')
    const treatmentOperations = readSource('src/core/editing/treatment-operations.ts')
    const framingPresets = readSource('src/core/editing/framing-presets.ts')
    const videoSurface = readSource('src/renderer/src/app/video-surface.tsx')
    const treatmentControl = readSource('src/renderer/src/app/editing-treatment-control.tsx')
    const framingPresetControl = readSource('src/renderer/src/app/editing-framing-preset-control.tsx')
    const filterControl = readSource('src/renderer/src/app/editing-filter-control.tsx')
    const filterOperations = readSource('src/core/editing/filter-operations.ts')
    const transitionControl = readSource('src/renderer/src/app/editing-transition-control.tsx')
    const clipMotionControl = readSource('src/renderer/src/app/editing-clip-motion-control.tsx')
    const transitionOperations = readSource('src/core/editing/transition-operations.ts')
    const graphicControl = readSource('src/renderer/src/app/editing-graphic-control.tsx')
    const graphicEditor = readSource('src/renderer/src/app/editing-graphic-editor.tsx')
    const graphicOperations = readSource('src/core/editing/graphic-operations.ts')
    const elementAssets = readSource('src/core/editing/element-assets.ts')
    const elementAssetHook = readSource('src/renderer/src/app/use-editing-element-assets.ts')
    const themes = readSource('src/core/editing/themes.ts')
    const frames = readSource('src/core/editing/frames.ts')
    const captionEffects = readSource('src/core/editing/caption-effects.ts')
    const themeHook = readSource('src/renderer/src/app/use-editing-themes.ts')
    const themeControl = readSource('src/renderer/src/app/editing-theme-control.tsx')
    const captionEffectControl = readSource('src/renderer/src/app/editing-caption-effect-control.tsx')
    const canvasControl = readSource('src/renderer/src/app/editing-canvas-control.tsx')
    const captionLayoutControl = readSource('src/renderer/src/app/editing-caption-layout-control.tsx')
    const captionLayout = readSource('src/core/editing/caption-layout.ts')
    const safeAreaOverlay = readSource('src/renderer/src/app/editing-safe-area-overlay.tsx')
    const canvases = readSource('src/core/editing/canvases.ts')
    const graphicOverlay = readSource('src/renderer/src/app/editing-graphic-overlay.tsx')
    const graphicLayout = readSource('src/core/editing/graphic-layout.ts')
    const captionCanvasOverlay = readSource('src/renderer/src/app/editing-caption-canvas-overlay.tsx')
    const graphicCanvasOverlay = readSource('src/renderer/src/app/editing-graphic-canvas-overlay.tsx')
    const graphicRasterizer = readSource('src/desktop/timeline-graphic-rasterizer.ts')
    const subtitleText = readSource('src/renderer/src/subtitle-text.tsx')
    const subtitleOverlay = readSource('src/renderer/src/subtitle-overlay.tsx')
    const subtitleAss = readSource('src/core/media/subtitle-ass.ts')
    const selection = readSource('src/core/editing/selection.ts')
    const selectionOperations = readSource('src/core/editing/selection-operations.ts')
    const selectionActions = readSource('src/renderer/src/app/editing-selection-actions.ts')
    const overlayTrackOperations = readSource('src/core/editing/overlay-track-operations.ts')
    const overlayTrackDnd = readSource('src/renderer/src/app/editing-overlay-track-dnd.ts')
    const trackTrim = readSource('src/renderer/src/app/editing-track-trim.ts')
    const timelineExport = readSource('src/core/media/timeline-export.ts')
    const timelineExportIpc = readSource('src/desktop/ipc-timeline-export.ts')
    const smokeScript = readSource('scripts/smoke-editing-script.ts')
    const captionReloadSmoke = readSource('scripts/smoke-editing-caption-reload.ts')
    const bilingualCaptionSmoke = readSource('scripts/smoke-bilingual-caption-export.ts')

    expect(stage).toContain("app.isEditingMode ? <EditingTimeline /> : <PlaybackControls />")
    expect(timeline).toContain('data-testid="editing-timeline"')
    expect(timeline).toContain('getEditingFramingKeyframes')
    expect(timeline).toContain('data-testid={`editing-framing-marker-${Math.round(keyframe.at * 1000)}`}')
    expect(timeline).toContain('app.selectEditingClip(clip.id)')
    expect(rangeTrack).toContain('data-testid="editing-track"')
    expect(timeline).toContain('app.splitEditingClip')
    expect(timeline).toContain('app.trimEditingClipLeft')
    expect(timeline).toContain('app.trimEditingClipRight')
    expect(timeline).toContain('app.deleteEditingClip')
    expect(timeline).toContain('app.exportEditingTimeline')
    expect(timeline).toContain('app.isExportingClip')
    expect(timeline).toContain('app.undoEditing')
    expect(timeline).toContain('app.redoEditing')
    expect(timeline).toContain('app.newEditingProject')
    expect(timeline).toContain('app.openEditingProjectFile')
    expect(timeline).toContain('app.saveEditingProjectFile')
    expect(timeline).toContain('app.resetEditingProject')
    expect(timeline).toContain('app.reorderEditingClips')
    expect(timelineSelection).toContain('app.selectEditingClip')
    expect(timeline).toContain('<EditingCaptionTrack')
    expect(captionTrack).toContain('data-testid="editing-caption-track"')
    expect(captionTrack).toContain('onMoveCaption')
    expect(captionTrack).toContain('snapEditedTime')
    expect(captionTrack).toContain('snapPoints?: readonly number[]')
    expect(captionTrack).toContain('event.shiftKey ? 1 : 0.1')
    expect(graphicTrack).toContain('snapEditedTime')
    expect(graphicTrack).toContain('snapPoints?: readonly number[]')
    expect(graphicTrack).toContain('event.shiftKey ? 1 : 0.1')
    expect(videoBlockTrack).toContain('snapEditedTime')
    expect(videoBlockTrack).toContain('snapPoints?: readonly number[]')
    expect(videoBlockTrack).toContain('event.shiftKey ? 1 : 0.1')
    expect(timeline).toContain('const overlaySnapPoints')
    expect(timeline).toContain('snapPoints={overlaySnapPoints}')
    expect(captionActions).toContain('moveEditingCaption')
    expect(captionEffect).toContain('sourceKey')
    expect(captionEffect).toContain('sourceRevisionKey')
    expect(captionEffect).toContain("kind: 'source'")
    expect(captionEffect).toContain("kind: 'translation'")
    expect(captionEffect).toContain('forceReloadEditingCaptions')
    expect(captionEffect).toContain('keepCurrentEditingCaptions')
    expect(timeline).toContain('<EditingCaptionReloadConflict')
    expect(captionReloadConflict).toContain('data-testid="editing-caption-reload-force"')
    expect(captionReloadConflict).toContain('data-testid="editing-caption-reload-preview"')
    expect(captionReloadConflict).toContain('data-testid="editing-caption-reload-search"')
    expect(captionReloadConflict).toContain('data-testid="editing-caption-reload-previous"')
    expect(captionReloadConflict).toContain('data-testid="editing-caption-reload-next"')
    expect(captionReloadConflict).toContain('data-testid="editing-caption-reload-time-start"')
    expect(captionReloadConflict).toContain('data-testid="editing-caption-reload-time-end"')
    expect(captionReloadConflict).toContain('editing-caption-reload-seek-current-')
    expect(captionReloadConflict).toContain('editing-caption-reload-seek-incoming-')
    expect(captionReloadConflict).toContain('onSelectScriptSegment')
    expect(scriptPanel).toContain('data-testid={`editing-script-row-${segment.id}`}')
    expect(captionTrack).toContain('data-testid={`editing-caption-item-${caption.id}`}')
    expect(timeline).toContain('onSelectScriptSegment={selectScriptSegment}')
    expect(timeline).toContain("selectTimelineItem('caption', segmentId)")
    expect(timeline).toContain('onSeek={app.seekEditingTime}')
    expect(timeline).toContain('data-testid="editing-time-readout"')
    expect(subtitleReloadCopy).toContain("'zh-CN'")
    expect(subtitleReloadCopy).toContain("'en-US'")
    expect(subtitleReloadCopy).toContain('searchPlaceholder')
    expect(subtitleReloadCopy).toContain('timeRange')
    expect(captionLoader).toContain('createEditingCaptionPathCandidates')
    expect(exportAction).toContain('serializeEditingCaptionsToSrt')
    expect(exportAction).toContain('subtitleText')
    expect(timeline).toContain('<EditingAudioControl')
    expect(timeline).toContain('app.setEditingClipVolume')
    expect(timeline).toContain('<EditingRangeTrack')
    expect(timeline).toContain('app.deleteEditingRange')
    expect(audioControl).toContain('editing-audio-range')
    expect(rangeTrack).toContain('setPointerCapture')
    expect(rangeTrack).toContain('deleteSelectedRange')
    expect(timeline).toContain('<EditingClipBoundaryHandles')
    expect(timeline).toContain('app.updateEditingClipBoundary')
    expect(boundaryHandles).toContain('setPointerCapture')
    expect(boundaryHandles).toContain('onCommit(span.clip.id, current.boundary, current.currentSeconds)')
    expect(timeline).toContain('<EditingExportSummary')
    expect(exportSummary).toContain('data-testid="editing-export-summary"')
    expect(exportSummary).toContain('formatResolution')
    expect(exportSummary).toContain('isEditingClipMuted')
    expect(timeline).toContain('<EditingExportConfirmDialog')
    expect(timeline).toContain('setIsExportConfirmOpen(true)')
    expect(timeline).toContain('data-testid="editing-export"')
    expect(exportConfirm).toContain('useModalFocusTrap')
    expect(exportConfirm).toContain('data-testid="editing-export-confirm"')
    expect(ffmpegCapabilityStatus).toContain('data-testid="editing-export-capability"')
    expect(exportConfirm).toContain('useFfmpegCapabilities')
    expect(clipExport).toContain('useFfmpegCapabilities')
    expect(timeline).toContain('<EditingCanvasControl')
    expect(timeline).toContain('app.setEditingCanvasPreset')
    expect(canvasControl).toContain('data-testid="editing-canvas-control"')
    expect(safeAreaOverlay).toContain('data-testid="editing-safe-area-overlay"')
    expect(stage).toContain('<EditingSafeAreaOverlay')
    expect(videoSurface).toContain('objectFit: editingCanvas.fitMode')
    expect(exportAction).toContain('fitMode: canvas.fitMode')
    expect(canvases).toContain("'portrait'")
    expect(timeline).toContain('<EditingCaptionLayoutControl')
    expect(timeline).toContain('app.setEditingCaptionLayout')
    expect(captionLayoutControl).toContain('data-testid="editing-caption-layout-control"')
    expect(captionLayoutControl).toContain('editing-caption-layout-${line}-${slider.key}')
    expect(captionLayout).toContain('DEFAULT_EDITING_CAPTION_LAYOUT')
    expect(stage).toContain('editingCaptionLayout={editingCaptionLayout}')
    expect(stage).toContain('<EditingCaptionCanvasOverlay')
    expect(captionCanvasOverlay).toContain('updateEditingCaptionLayout')
    expect(captionCanvasOverlay).toContain('data-testid={`editing-caption-canvas-overlay-${line}`}')
    expect(captionCanvasOverlay).toContain("window.addEventListener('pointermove'")
    expect(captionCanvasOverlay).toContain("window.addEventListener('pointercancel'")
    expect(subtitleOverlay).toContain('is-editing-caption')
    expect(subtitleText).toContain('maxWidthPx')
    expect(subtitleAss).toContain('getAssCaptionLayoutTag')
    expect(bilingualCaptionSmoke).toContain("mode: 'burn-subtitle'")
    expect(bilingualCaptionSmoke).toContain('Style: Translation')
    expect(exportConfirm).toContain('outputFileName')
    expect(exportConfirm).toContain('chooseTimelineExportPath')
    expect(exportConfirm).toContain('outputVideoPath')
    expect(timeline).toContain('auditEditingExport')
    expect(exportAudit).toContain('missing-source-file')
    expect(exportConfirm).toContain('data-testid="editing-export-audit"')
    expect(exportAction).toContain('requestedMode')
    expect(playbackEffect).toContain('applyClipAudio')
    expect(timeline).toContain('app.addEditingSources')
    expect(timeline).toContain('<EditingScriptPanel')
    expect(timeline).toContain('app.selectEditingScriptSegment')
    expect(timeline).toContain('app.updateEditingScriptText')
    expect(timeline).toContain('app.deleteEditingScriptSegment')
    expect(timeline).toContain('app.restoreEditingScriptSegment')
    expect(timeline).toContain('app.deleteEditingScriptWord')
    expect(timeline).toContain('app.replaceEditingScriptWord')
    expect(timeline).toContain('app.deleteEditingScriptWords')
    expect(scriptPanel).toContain('data-testid="editing-script-panel"')
    expect(scriptPanel).toContain('data-testid={`editing-script-input-${segment.id}`}')
    expect(scriptPanel).toContain('data-testid={`editing-script-save-${segment.id}`}')
    expect(scriptPanel).toContain('data-testid={`editing-script-word-${segment.id}-${index}`}')
    expect(scriptPanel).toContain('editing-script-delete-selected')
    expect(scriptPanel).toContain('editing-script-filler-delete')
    expect(scriptActions).toContain('restoreSourceVideoRange')
    expect(scriptActions).toContain('removeSourceVideoRanges')
    expect(scriptActions).toContain('updateEditingScriptText')
    expect(scriptActions).toContain('deleteEditingScriptWord')
    expect(scriptActions).toContain('replaceEditingScriptWord')
    expect(scriptActions).toContain('deleteEditingScriptWords')
    expect(scriptActions).toContain('getEditingScriptWordSourceRange')
    expect(scriptOperations).toContain('mergeEditingScriptSegments')
    expect(scriptOperations).toContain('getEditingScriptWordSourceRange')
    expect(scriptOperations).toContain('removeEditingScriptWord')
    expect(scriptOperations).toContain('removeEditingScriptWords')
    expect(scriptOperations).toContain('replaceEditingScriptWord')
    expect(actionHelpers).toContain('removeEditingCaptionInterval')
    expect(scriptOperations).toContain('updateEditingSourceCaptionText')
    expect(snapping).toContain('snapEditedTime')
    expect(timeline).toContain('snapPoints={snapPoints}')
    expect(timeline).toContain('data-editing-selection-kind="clip"')
    expect(timelineSelection).toContain('beginTimelineMarquee')
    expect(timeline).toContain('onKeyDown={handleTimelineKeyDown}')
    expect(timeline).toContain('data-testid="editing-selection-toolbar"')
    expect(timeline).toContain('data-testid="editing-delete-selection"')
    expect(timeline).toContain('data-testid="editing-selection-move-left"')
    expect(timeline).toContain('data-testid="editing-selection-move-right"')
    expect(timeline).toContain('data-testid="editing-duplicate-selection"')
    expect(timeline).toContain('app.moveEditingSelection')
    expect(timelineSelection).toContain('app.deleteEditingSelection')
    expect(timelineSelection).toContain('duplicateTimelineSelection')
    expect(timelineSelection).toContain("event.key.toLowerCase() === 'd'")
    expect(captionTrack).toContain('data-editing-selection-kind="caption"')
    expect(graphicTrack).toContain('data-editing-selection-kind="graphic"')
    expect(videoBlockTrack).toContain('data-editing-selection-kind="videoBlock"')
    expect(actions).toContain('deleteEditingSelection')
    expect(selection).toContain('editingSelectionCount')
    expect(selectionOperations).toContain('moveEditingSelection')
    expect(selectionOperations).toContain('duplicateEditingSelection')
    expect(selectionOperations).toContain('clampGroupDelta')
    expect(selectionActions).toContain('deleteVideoClipsById')
    expect(timeline).toContain('getEditingOverlayTrackOrder')
    expect(timeline).toContain('overlayTrackOrder.map(renderOverlayTrack)')
    expect(timeline).toContain('onReorderTrack={reorderOverlayTracks}')
    expect(timeline).toContain('trackKind="captions"')
    expect(overlayTrackOperations).toContain('reorderEditingOverlayTracks')
    expect(overlayTrackDnd).toContain('EDITING_OVERLAY_TRACK_DRAG_TYPE')
    expect(actions).toContain('reorderEditingOverlayTracks')
    expect(captionActions).toContain('resizeEditingCaption')
    expect(captionTrack).toContain('onResizeCaption')
    expect(graphicTrack).toContain('editing-timeline-trim-handle')
    expect(videoBlockTrack).toContain('editing-timeline-trim-handle')
    expect(trackTrim).toContain('updateEditingTrackTrim')
    expect(smokeScript).toContain('graphicTrimBefore')
    expect(captionReloadSmoke).toContain('editing-caption-reload-conflict')
    expect(captionReloadSmoke).toContain('editing-caption-reload-keep')
    expect(captionReloadSmoke).toContain('editing-caption-reload-force')
    expect(smokeScript).toContain('filterAfterSliderDrag')
    expect(smokeScript).toContain('filterAfterOneUndo')
    expect(smokeScript).toContain('scriptWordCount')
    expect(smokeScript).toContain('wordDeleteRestored')
    expect(exportAction).toContain('overlayTrackOrder: project.overlayTrackOrder')
    expect(timelineExportIpc).toContain('overlayTrackOrder: request.overlayTrackOrder')
    expect(timelineExport).toContain('options.overlayTrackOrder')
    expect(timeline).toContain('<EditingTreatmentControl')
    expect(timeline).toContain('<EditingFramingPresetControl')
    expect(timeline).toContain('app.applyEditingFramingPreset')
    expect(framingPresets).toContain('EDITING_FRAMING_PRESETS')
    expect(framingPresets).toContain('applyEditingFramingPreset')
    expect(framingPresetControl).toContain('data-testid="editing-framing-preset-control"')
    expect(framingPresetControl).toContain('isEditingFramingPresetAllowed')
    expect(timeline).toContain('app.setEditingClipTreatment')
    expect(treatmentControl).toContain('data-testid="editing-treatment-control"')
    expect(treatmentControl).toContain('data-testid={`editing-treatment-${optionTreatment}`}')
    expect(treatmentControl).toContain('data-orientation-allowed={allowed ? \'true\' : \'false\'}')
    expect(treatmentControl).toContain('isEditingFramingTreatmentAllowed')
    expect(timeline).toContain('getEditingFramingOrientation')
    expect(treatmentControl).toContain("treatment: 'corner-br'")
    expect(treatmentControl).toContain('data-testid="editing-treatment-anchor-left"')
    expect(treatmentControl).toContain('onPreview')
    expect(treatmentControl).toContain('onPointerUp={commitScale}')
    expect(treatmentOperations).toContain('updateEditingClipTreatment')
    expect(timeline).toContain('<EditingFilterControl')
    expect(timeline).toContain('app.setEditingClipFilter')
    expect(filterControl).toContain('data-testid="editing-filter-control"')
    expect(filterControl).toContain('onPreview')
    expect(filterControl).toContain('onPointerUp={commitPreview}')
    expect(clipActions).toContain('previewEditingClipFilter')
    expect(clipActions).toContain('previewEditingClipTreatment')
    expect(videoSurface).toContain('editingClipPreview')
    expect(filterOperations).toContain('buildEditingClipFilterCss')
    expect(timeline).toContain('<EditingTransitionControl')
    expect(timeline).toContain('app.setEditingClipTransition')
    expect(transitionControl).toContain('data-testid="editing-transition-control"')
    expect(transitionControl).toContain('<TransitionPreview type={type} />')
    expect(transitionControl).toContain('editing-transition-preview-${previewType}')
    expect(transitionOperations).toContain('updateEditingClipTransition')
    expect(transitionOperations).toContain("'circleopen'")
    expect(transitionOperations).toContain("'crosszoom'")
    expect(videoSurface).toContain("transition?.type === 'circleopen'")
    expect(videoSurface).toContain("transition?.type === 'crosszoom'")
    expect(timelineExport).toContain("case 'circleopen': return 'circleopen'")
    expect(timeline).toContain('<EditingClipMotionControl')
    expect(timeline).toContain('app.setEditingClipMotion')
    expect(clipMotionControl).toContain('data-testid="editing-clip-motion-control"')
    expect(clipMotionControl).toContain('data-testid={`editing-clip-motion-enter-${value}`}')
    expect(clipMotionControl).toContain('data-testid={`editing-clip-motion-exit-${value}`}')
    expect(clipMotionControl).toContain('data-testid="editing-clip-motion-duration"')
    expect(timeline).toContain('<EditingGraphicControl')
    expect(timeline).toContain('<EditingGraphicTrack')
    expect(graphicControl).toContain('data-testid="editing-graphic-control"')
    expect(graphicControl).toContain('detailsRef.current.open = false')
    expect(graphicControl).toContain('editing-graphic-assets-search')
    expect(graphicEditor).toContain('data-testid="editing-graphic-save-asset"')
    expect(timeline).toContain('useEditingElementAssets')
    expect(elementAssets).toContain('EDITING_ELEMENT_ASSET_LIMIT')
    expect(elementAssetHook).toContain('aivplayer.editing-element-assets.v1')
    expect(graphicEditor).toContain('data-testid="editing-graphic-editor"')
    expect(graphicEditor).toContain('data-testid="editing-graphic-save"')
    expect(graphicEditor).toContain('data-testid="editing-graphic-edit-enter"')
    expect(graphicEditor).toContain('data-testid="editing-graphic-edit-exit"')
    expect(graphicEditor).toContain('data-testid="editing-graphic-edit-motion-duration"')
    expect(graphicOverlay).toContain('findVisibleEditingGraphics')
    expect(graphicOverlay).toContain('getEditingGraphicMotionStyle')
    expect(graphicRasterizer).toContain('getBoundingClientRect')
    expect(graphicRasterizer).toContain('image.crop(bounds)')
    expect(timelineExport).toContain('motion.exitMotion === \'none\' ? 0 : motion.durationSeconds')
    expect(graphicTrack).toContain('data-testid="editing-graphic-track"')
    expect(graphicTrack).toContain('setPointerCapture')
    expect(graphicTrack).toContain('onMove')
    expect(graphicOperations).toContain('createEditingGraphic')
    expect(graphicOperations).toContain('applyEditingGraphicTheme')
    expect(themes).toContain('BUILTIN_EDITING_THEMES')
    expect(themes).toContain('normalizeEditingThemes')
    expect(frames).toContain('BUILTIN_EDITING_FRAMES')
    expect(frames).toContain('--editing-frame-card-background')
    expect(captionEffects).toContain('BUILTIN_EDITING_CAPTION_EFFECTS')
    expect(captionEffects).toContain('getEditingCaptionWordEffectState')
    expect(themeHook).toContain('aivplayer.editing-themes.v1')
    expect(themeControl).toContain('data-testid="editing-theme-control"')
    expect(themeControl).toContain('editing-frame-preview-')
    expect(captionEffectControl).toContain('data-testid="editing-caption-effect-control"')
    expect(timeline).toContain('<EditingCaptionEffectControl')
    expect(timeline).toContain('applyEditingFrameTheme')
    expect(graphicOverlay).toContain('is-frame-')
    expect(graphicOverlay).toContain('data-editing-graphic-id')
    expect(graphicLayout).toContain('updateEditingGraphicTransform')
    expect(graphicRasterizer).toContain('frameId')
    expect(graphicRasterizer).toContain('getEditingGraphicTransform')
    expect(stage).toContain('<EditingGraphicCanvasOverlay')
    expect(graphicCanvasOverlay).toContain('data-testid="editing-graphic-canvas-overlay"')
    expect(graphicCanvasOverlay).toContain("window.addEventListener('pointermove'")
    expect(graphicCanvasOverlay).toContain('rotationDegrees')
    expect(subtitleText).toContain('is-effect-')
    expect(subtitleText).toContain('getEditingCaptionWordEffectState')
    expect(subtitleOverlay).toContain('editingCaptionEffect')
    expect(subtitleAss).toContain('getEditingCaptionEffectAssPrefix')
    expect(timeline).toContain('<EditingThemeControl')
    expect(videoSurface).toContain('is-punch-in')
    expect(videoSurface).toContain('transformOrigin')
    expect(videoSurface).toContain('buildEditingClipFilterCss')
    expect(exportAction).toContain('treatmentScale')
    expect(timeline).toContain('useEditingFilmstrips')
    expect(timeline).toContain('filmstrips[span.clip.sourceId]')
    expect(actions).toContain('createEditingClipActions(model)')
    expect(actions).toContain('createEditingSourceActions(model, derived)')
    expect(timeline).toContain('data-testid="editing-add-media"')
    expect(actions).toContain('useEditingPlaybackEffect(model)')
    expect(actions).toContain('seekEditingTime: (seconds: number) => seekEditingTime(model, seconds)')
    expect(actions).toContain('loadEditingProject(source)')
    expect(actionHelpers).toContain('saveEditingProject(nextProject)')
    expect(storage).toContain('aivplayer.editing-projects.v1')
    expect(captionEffect).toContain('loadEditingCaptions')
    expect(readSource('src/renderer/src/app/use-editing-playback-effect.ts')).toContain('loadedmetadata')
  })

  it('keeps the timeline stylesheet semantic and token-driven', () => {
    const playerStyles = readSource('src/renderer/src/styles/player.css')
    const shellStyles = readSource('src/renderer/src/styles/player/editing-timeline-shell.css')
    const actionStyles = readSource('src/renderer/src/styles/player/editing-timeline-actions.css')
    const trackStyles = readSource('src/renderer/src/styles/player/editing-timeline-track.css')
    const clipStyles = readSource('src/renderer/src/styles/player/editing-timeline-clips.css')
    const filmstripStyles = readSource('src/renderer/src/styles/player/editing-timeline-filmstrip.css')
    const captionStyles = readSource('src/renderer/src/styles/player/editing-timeline-captions.css')
    const audioStyles = readSource('src/renderer/src/styles/player/editing-timeline-audio.css')
    const rangeStyles = readSource('src/renderer/src/styles/player/editing-timeline-range.css')
    const boundaryStyles = readSource('src/renderer/src/styles/player/editing-timeline-boundaries.css')
    const exportSummaryStyles = readSource('src/renderer/src/styles/player/editing-timeline-export-summary.css')
    const exportTargetStyles = readSource('src/renderer/src/styles/player/editing-timeline-export-target.css')
    const scriptStyles = readSource('src/renderer/src/styles/player/editing-timeline-script.css')
    const scriptEditorStyles = readSource('src/renderer/src/styles/player/editing-timeline-script-editor.css')
    const treatmentStyles = readSource('src/renderer/src/styles/player/editing-timeline-treatment.css')
    const filterStyles = readSource('src/renderer/src/styles/player/editing-timeline-filter.css')
    const transitionStyles = readSource('src/renderer/src/styles/player/editing-timeline-transition.css')
    const transitionPreviewStyles = readSource('src/renderer/src/styles/player/editing-timeline-transition-preview.css')
    const clipMotionStyles = readSource('src/renderer/src/styles/player/editing-timeline-clip-motion.css')
    const graphicStyles = readSource('src/renderer/src/styles/player/editing-timeline-graphic.css')
    const graphicTrackStyles = readSource('src/renderer/src/styles/player/editing-timeline-graphic-track.css')
    const graphicOverlayStyles = readSource('src/renderer/src/styles/player/editing-graphic-overlay.css')
    const graphicCanvasStyles = readSource('src/renderer/src/styles/player/editing-graphic-canvas-overlay.css')
    const themeStyles = readSource('src/renderer/src/styles/player/editing-timeline-theme.css')
    const captionEffectStyles = readSource('src/renderer/src/styles/player/editing-timeline-caption-effect.css')
    const subtitlePresetStyles = readSource('src/renderer/src/styles/player/subtitle-presets.css')
    const selectionStyles = readSource('src/renderer/src/styles/player/editing-timeline-selection.css')

    expect(playerStyles).toContain("@import './player/editing-timeline-shell.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-actions.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-track.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-selection.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-clips.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-filmstrip.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-captions.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-audio.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-range.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-boundaries.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-export-summary.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-export-target.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-script.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-script-editor.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-treatment.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-transition.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-transition-preview.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-clip-motion.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-graphic.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-graphic-track.css';")
    expect(playerStyles).toContain("@import './player/editing-graphic-overlay.css';")
    expect(playerStyles).toContain("@import './player/editing-graphic-canvas-overlay.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-caption-effect.css';")
    const baseTimelineStyles = shellStyles + actionStyles + trackStyles + clipStyles + filmstripStyles + captionStyles + audioStyles + rangeStyles + boundaryStyles + exportSummaryStyles + exportTargetStyles + scriptStyles + scriptEditorStyles + treatmentStyles + filterStyles + transitionStyles + transitionPreviewStyles + clipMotionStyles + graphicStyles + graphicTrackStyles + graphicOverlayStyles + graphicCanvasStyles + selectionStyles
    expect(baseTimelineStyles).toContain('var(--bg-control)')
    expect(baseTimelineStyles).toContain('var(--accent)')
    expect(clipStyles).toContain('.editing-framing-marker')
    expect(baseTimelineStyles).not.toMatch(/#[0-9a-fA-F]{3,8}/)
    expect(themeStyles).toContain('.editing-theme-preview.is-warm')
    expect(captionEffectStyles).toContain('.editing-caption-effect-option.is-active')
    expect(subtitlePresetStyles).toContain('.subtitle-text.is-effect-word-pop')
  })
})
