import { describe, expect, it } from 'vitest'
import { readSource } from './test-source-utils'

describe('editing timeline source contracts', () => {
  it('renders the editing rail from the player stage and exposes core edit actions', () => {
    const stage = readSource('src/renderer/src/app/player-stage.tsx')
    const timeline = readSource('src/renderer/src/app/editing-timeline.tsx')
    const actions = readSource('src/renderer/src/app/use-editing-actions.ts')
    const actionHelpers = readSource('src/renderer/src/app/editing-action-helpers.ts')
    const storage = readSource('src/renderer/src/app/editing-project-storage.ts')
    const captionEffect = readSource('src/renderer/src/app/use-editing-caption-effect.ts')
    const captionTrack = readSource('src/renderer/src/app/editing-caption-track.tsx')
    const captionActions = readSource('src/renderer/src/app/editing-caption-actions.ts')
    const captionLoader = readSource('src/renderer/src/app/editing-caption-loader.ts')
    const exportAction = readSource('src/renderer/src/app/editing-export-action.ts')
    const audioControl = readSource('src/renderer/src/app/editing-audio-control.tsx')
    const rangeTrack = readSource('src/renderer/src/app/editing-range-track.tsx')
    const boundaryHandles = readSource('src/renderer/src/app/editing-clip-boundary-handles.tsx')
    const exportSummary = readSource('src/renderer/src/app/editing-export-summary.tsx')
    const exportConfirm = readSource('src/renderer/src/app/editing-export-confirm-dialog.tsx')
    const playbackEffect = readSource('src/renderer/src/app/use-editing-playback-effect.ts')
    const scriptPanel = readSource('src/renderer/src/app/editing-script-panel.tsx')
    const scriptActions = readSource('src/renderer/src/app/editing-script-actions.ts')
    const scriptOperations = readSource('src/core/editing/script-operations.ts')
    const snapping = readSource('src/core/editing/timeline-snapping.ts')
    const treatmentOperations = readSource('src/core/editing/treatment-operations.ts')
    const videoSurface = readSource('src/renderer/src/app/video-surface.tsx')
    const treatmentControl = readSource('src/renderer/src/app/editing-treatment-control.tsx')
    const filterControl = readSource('src/renderer/src/app/editing-filter-control.tsx')
    const filterOperations = readSource('src/core/editing/filter-operations.ts')
    const transitionControl = readSource('src/renderer/src/app/editing-transition-control.tsx')
    const transitionOperations = readSource('src/core/editing/transition-operations.ts')
    const graphicControl = readSource('src/renderer/src/app/editing-graphic-control.tsx')
    const graphicEditor = readSource('src/renderer/src/app/editing-graphic-editor.tsx')
    const graphicTrack = readSource('src/renderer/src/app/editing-graphic-track.tsx')
    const graphicOperations = readSource('src/core/editing/graphic-operations.ts')

    expect(stage).toContain("app.isEditingMode ? <EditingTimeline /> : <PlaybackControls />")
    expect(timeline).toContain('data-testid="editing-timeline"')
    expect(timeline).toContain('data-testid="editing-track"')
    expect(timeline).toContain('app.splitEditingClip')
    expect(timeline).toContain('app.trimEditingClipLeft')
    expect(timeline).toContain('app.trimEditingClipRight')
    expect(timeline).toContain('app.deleteEditingClip')
    expect(timeline).toContain('app.exportEditingTimeline')
    expect(timeline).toContain('app.isExportingClip')
    expect(timeline).toContain('app.undoEditing')
    expect(timeline).toContain('app.redoEditing')
    expect(timeline).toContain('app.newEditingProject')
    expect(timeline).toContain('app.openEditingProjectFile')
    expect(timeline).toContain('app.saveEditingProjectFile')
    expect(timeline).toContain('app.resetEditingProject')
    expect(timeline).toContain('app.reorderEditingClips')
    expect(timeline).toContain('app.selectEditingClip')
    expect(timeline).toContain('<EditingCaptionTrack')
    expect(captionTrack).toContain('data-testid="editing-caption-track"')
    expect(captionTrack).toContain('onMoveCaption')
    expect(captionActions).toContain('moveEditingCaption')
    expect(captionEffect).toContain('sourceKey')
    expect(captionLoader).toContain('createEditingCaptionPathCandidates')
    expect(exportAction).toContain('serializeEditingCaptionsToSrt')
    expect(exportAction).toContain('subtitleText')
    expect(timeline).toContain('<EditingAudioControl')
    expect(timeline).toContain('app.setEditingClipVolume')
    expect(timeline).toContain('<EditingRangeTrack')
    expect(timeline).toContain('app.deleteEditingRange')
    expect(audioControl).toContain('editing-audio-range')
    expect(rangeTrack).toContain('setPointerCapture')
    expect(rangeTrack).toContain('deleteSelectedRange')
    expect(timeline).toContain('<EditingClipBoundaryHandles')
    expect(timeline).toContain('app.updateEditingClipBoundary')
    expect(boundaryHandles).toContain('setPointerCapture')
    expect(boundaryHandles).toContain('onCommit(span.clip.id, current.boundary, current.currentSeconds)')
    expect(timeline).toContain('<EditingExportSummary')
    expect(exportSummary).toContain('data-testid="editing-export-summary"')
    expect(exportSummary).toContain('formatResolution')
    expect(exportSummary).toContain('isEditingClipMuted')
    expect(timeline).toContain('<EditingExportConfirmDialog')
    expect(timeline).toContain('setIsExportConfirmOpen(true)')
    expect(timeline).toContain('data-testid="editing-export"')
    expect(exportConfirm).toContain('useModalFocusTrap')
    expect(exportConfirm).toContain('data-testid="editing-export-confirm"')
    expect(exportConfirm).toContain('outputFileName')
    expect(exportConfirm).toContain('chooseTimelineExportPath')
    expect(exportConfirm).toContain('outputVideoPath')
    expect(exportAction).toContain('requestedMode')
    expect(playbackEffect).toContain('applyClipAudio')
    expect(timeline).toContain('app.addEditingSources')
    expect(timeline).toContain('<EditingScriptPanel')
    expect(timeline).toContain('app.selectEditingScriptSegment')
    expect(timeline).toContain('app.deleteEditingScriptSegment')
    expect(timeline).toContain('app.restoreEditingScriptSegment')
    expect(scriptPanel).toContain('data-testid="editing-script-panel"')
    expect(scriptActions).toContain('restoreSourceVideoRange')
    expect(scriptActions).toContain('removeSourceVideoRanges')
    expect(scriptOperations).toContain('mergeEditingScriptSegments')
    expect(snapping).toContain('snapEditedTime')
    expect(timeline).toContain('snapPoints={snapPoints}')
    expect(timeline).toContain('<EditingTreatmentControl')
    expect(timeline).toContain('app.setEditingClipTreatment')
    expect(treatmentControl).toContain('data-testid="editing-treatment-control"')
    expect(treatmentControl).toContain('data-testid="editing-treatment-punch-in"')
    expect(treatmentControl).toContain('data-testid="editing-treatment-anchor-left"')
    expect(treatmentOperations).toContain('updateEditingClipTreatment')
    expect(timeline).toContain('<EditingFilterControl')
    expect(timeline).toContain('app.setEditingClipFilter')
    expect(filterControl).toContain('data-testid="editing-filter-control"')
    expect(filterOperations).toContain('buildEditingClipFilterCss')
    expect(timeline).toContain('<EditingTransitionControl')
    expect(timeline).toContain('app.setEditingClipTransition')
    expect(transitionControl).toContain('data-testid="editing-transition-control"')
    expect(transitionOperations).toContain('updateEditingClipTransition')
    expect(timeline).toContain('<EditingGraphicControl')
    expect(timeline).toContain('<EditingGraphicTrack')
    expect(graphicControl).toContain('data-testid="editing-graphic-control"')
    expect(graphicControl).toContain('detailsRef.current.open = false')
    expect(graphicEditor).toContain('data-testid="editing-graphic-editor"')
    expect(graphicEditor).toContain('data-testid="editing-graphic-save"')
    expect(graphicTrack).toContain('data-testid="editing-graphic-track"')
    expect(graphicTrack).toContain('setPointerCapture')
    expect(graphicTrack).toContain('onMove')
    expect(graphicOperations).toContain('createEditingGraphic')
    expect(videoSurface).toContain('is-punch-in')
    expect(videoSurface).toContain('transformOrigin')
    expect(videoSurface).toContain('buildEditingClipFilterCss')
    expect(exportAction).toContain('treatmentScale')
    expect(timeline).toContain('useEditingFilmstrips')
    expect(timeline).toContain('filmstrips[span.clip.sourceId]')
    expect(actions).toContain('createEditingClipActions(model)')
    expect(actions).toContain('createEditingSourceActions(model, derived)')
    expect(timeline).toContain('data-testid="editing-add-media"')
    expect(actions).toContain('useEditingPlaybackEffect(model)')
    expect(actions).toContain('seekEditingTime: (seconds: number) => seekEditingTime(model, seconds)')
    expect(actions).toContain('loadEditingProject(source)')
    expect(actionHelpers).toContain('saveEditingProject(nextProject)')
    expect(storage).toContain('aivplayer.editing-projects.v1')
    expect(captionEffect).toContain('loadEditingCaptions')
    expect(readSource('src/renderer/src/app/use-editing-playback-effect.ts')).toContain('loadedmetadata')
  })

  it('keeps the timeline stylesheet semantic and token-driven', () => {
    const playerStyles = readSource('src/renderer/src/styles/player.css')
    const shellStyles = readSource('src/renderer/src/styles/player/editing-timeline-shell.css')
    const actionStyles = readSource('src/renderer/src/styles/player/editing-timeline-actions.css')
    const trackStyles = readSource('src/renderer/src/styles/player/editing-timeline-track.css')
    const clipStyles = readSource('src/renderer/src/styles/player/editing-timeline-clips.css')
    const filmstripStyles = readSource('src/renderer/src/styles/player/editing-timeline-filmstrip.css')
    const captionStyles = readSource('src/renderer/src/styles/player/editing-timeline-captions.css')
    const audioStyles = readSource('src/renderer/src/styles/player/editing-timeline-audio.css')
    const rangeStyles = readSource('src/renderer/src/styles/player/editing-timeline-range.css')
    const boundaryStyles = readSource('src/renderer/src/styles/player/editing-timeline-boundaries.css')
    const exportSummaryStyles = readSource('src/renderer/src/styles/player/editing-timeline-export-summary.css')
    const exportTargetStyles = readSource('src/renderer/src/styles/player/editing-timeline-export-target.css')
    const scriptStyles = readSource('src/renderer/src/styles/player/editing-timeline-script.css')
    const treatmentStyles = readSource('src/renderer/src/styles/player/editing-timeline-treatment.css')
    const filterStyles = readSource('src/renderer/src/styles/player/editing-timeline-filter.css')
    const transitionStyles = readSource('src/renderer/src/styles/player/editing-timeline-transition.css')
    const graphicStyles = readSource('src/renderer/src/styles/player/editing-timeline-graphic.css')
    const graphicTrackStyles = readSource('src/renderer/src/styles/player/editing-timeline-graphic-track.css')
    const graphicOverlayStyles = readSource('src/renderer/src/styles/player/editing-graphic-overlay.css')

    expect(playerStyles).toContain("@import './player/editing-timeline-shell.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-actions.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-track.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-clips.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-filmstrip.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-captions.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-audio.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-range.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-boundaries.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-export-summary.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-export-target.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-script.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-treatment.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-transition.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-graphic.css';")
    expect(playerStyles).toContain("@import './player/editing-timeline-graphic-track.css';")
    expect(playerStyles).toContain("@import './player/editing-graphic-overlay.css';")
    expect(shellStyles + actionStyles + trackStyles + clipStyles + filmstripStyles + captionStyles + audioStyles + rangeStyles + boundaryStyles + exportSummaryStyles + exportTargetStyles + scriptStyles + treatmentStyles + filterStyles + transitionStyles + graphicStyles + graphicTrackStyles + graphicOverlayStyles).toContain('var(--bg-control)')
    expect(shellStyles + actionStyles + trackStyles + clipStyles + filmstripStyles + captionStyles + audioStyles + rangeStyles + boundaryStyles + exportSummaryStyles + exportTargetStyles + scriptStyles + treatmentStyles + filterStyles + transitionStyles + graphicStyles + graphicTrackStyles + graphicOverlayStyles).toContain('var(--accent)')
    expect(shellStyles + actionStyles + trackStyles + clipStyles + filmstripStyles + captionStyles + audioStyles + rangeStyles + boundaryStyles + exportSummaryStyles + exportTargetStyles + scriptStyles + treatmentStyles + filterStyles + transitionStyles + graphicStyles + graphicTrackStyles + graphicOverlayStyles).not.toMatch(/#[0-9a-fA-F]{3,8}/)
  })
})
