import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const projectRoot = process.cwd()
const releaseWorkflow = readFileSync(join(projectRoot, '.github/workflows/release.yml'), 'utf8')
const macosWorkflow = releaseWorkflow.slice(releaseWorkflow.indexOf('  build-macos:'), releaseWorkflow.indexOf('  build-windows:'))
const packageJson = readFileSync(join(projectRoot, 'package.json'), 'utf8')
const electronBuilder = readFileSync(join(projectRoot, 'electron-builder.yml'), 'utf8')
const artifactPolicy = readFileSync(join(projectRoot, 'scripts/release-artifact-policy.mjs'), 'utf8')
const remoteVerification = readFileSync(join(projectRoot, 'scripts/verify-remote-release.mjs'), 'utf8')
const releaseVersion = readFileSync(join(projectRoot, 'scripts/check-release-version.mjs'), 'utf8')
const platformRelease = readFileSync(join(projectRoot, 'scripts/check-platform-release-artifacts.mjs'), 'utf8')
const packageFormats = readFileSync(join(projectRoot, 'scripts/check-release-package-formats.mjs'), 'utf8')
const platformEvidence = readFileSync(join(projectRoot, 'scripts/check-platform-evidence.mjs'), 'utf8')
const releaseDryRun = readFileSync(join(projectRoot, 'scripts/release-dry-run.mjs'), 'utf8')
const macosFfmpegRuntime = readFileSync(join(projectRoot, 'scripts/check-macos-ffmpeg-runtime.ts'), 'utf8')
const buildWhisperMacos = readFileSync(join(projectRoot, 'scripts/build-whisper-macos.ts'), 'utf8')
const buildHeifSource = readFileSync(join(projectRoot, 'scripts/build-heif-source.ts'), 'utf8')

describe('release workflow source constraints', () => {
  it('uses ZIP payloads for the Windows NSIS installer without differential packaging', () => {
    expect(electronBuilder).toContain('useZip: true')
    expect(electronBuilder).toContain('differentialPackage: false')
  })

  it('keeps platform builds separate from release publishing', () => {
    expect(releaseWorkflow).not.toContain('GH_TOKEN:')
    expect(releaseWorkflow.match(/run: npm run build && npx electron-builder.*--publish never/g)).toHaveLength(5)
    expect(releaseWorkflow).toContain('run: npm run build && npx electron-builder --dir --publish never -c.mac.notarize=false')
    expect(releaseWorkflow).toContain('name: Build signed macOS app')
    expect(releaseWorkflow).toContain('name: Package notarized macOS app')
    expect(releaseWorkflow).not.toContain('build-snap')
    expect(releaseWorkflow).not.toContain('publish-snap')
    expect(releaseWorkflow).not.toContain('SNAPCRAFT_STORE_CREDENTIALS')
  })

  it('waits for all desktop artifacts before creating a release', () => {
    expect(releaseWorkflow).toContain('needs: [build-macos, build-windows, build-windows-arm64, build-linux, build-linux-arm64]')
    expect(releaseWorkflow).toContain('tag_name: ${{ inputs.tag || github.ref_name }}')
    expect(releaseWorkflow).toContain('release:create-manifest')
    expect(releaseWorkflow).toContain('release:check-manifest')
    expect(releaseWorkflow).toContain('release:check-version')
    expect(releaseWorkflow).toContain('artifacts/assembled/release-manifest.json')
    expect(releaseWorkflow).toContain('--commit "${{ github.sha }}"')
    expect(releaseWorkflow).toContain('--repository "${{ github.repository }}"')
    expect(releaseWorkflow).toContain('--workflow "${{ github.workflow }}"')
    expect(releaseWorkflow).toContain('--workflow-run-id "${{ github.run_id }}"')
    expect(releaseWorkflow).toContain('--workflow-run-attempt "${{ github.run_attempt }}"')
    expect(releaseWorkflow).toContain('name: Prepare release notes')
    expect(releaseWorkflow).toContain('cp "$notes" artifacts/assembled/release-notes.md')
    expect(releaseWorkflow).toContain('generate_release_notes: false')
    expect(releaseWorkflow).toContain('body_path: artifacts/assembled/release-notes.md')
  })

  it('publishes Vision Packs to R2 before creating the release', () => {
    expect(releaseWorkflow).toContain('Upload platform-specific Vision Packs to R2')
    expect(releaseWorkflow).toContain('CLOUDFLARE_API_TOKEN')
    expect(releaseWorkflow).toContain('aivplayer-releases/aivplayer/vision-pack/$version')
    expect(releaseWorkflow).toContain('复用 R2 归档校验值（跨版本复用）')
    expect(releaseWorkflow).toContain('content_manifest_url')
    expect(releaseWorkflow).toContain('name: Create GitHub Release')
  })

  it('supports a verify-only workflow dispatch without remote release writes', () => {
    expect(releaseWorkflow).toContain('verify_only:')
    expect(releaseWorkflow).toContain('description: \'Build and validate all release artifacts without creating a release\'')
    expect(releaseWorkflow).toContain('default: false')
    expect(releaseWorkflow).toContain('type: boolean')
    expect(releaseWorkflow.match(/github\.event_name != 'workflow_dispatch' \|\| inputs\.verify_only != true/g)).toHaveLength(6)
    expect(releaseWorkflow.indexOf('release:check-evidence')).toBeLessThan(releaseWorkflow.indexOf('Create GitHub Release'))
  })

  it('stages platform runtimes before packaging', () => {
    expect(releaseWorkflow.match(/release:check-runtime/g)).toHaveLength(10)
    expect(releaseWorkflow.match(/release:build-vision-pack/g)).toHaveLength(5)
    expect(releaseWorkflow.match(/release:report-package-size/g)).toHaveLength(5)
    expect(releaseWorkflow).not.toContain('release:prepare-vision-model -- --resource-dir')
    expect(releaseWorkflow.match(/release:write-runtime-metadata/g)).toHaveLength(5)
    expect(releaseWorkflow).toContain('release:build-whisper-macos')
    expect(releaseWorkflow).toContain('release:prepare-runtime -- --platform win32')
    expect(releaseWorkflow).toContain('release:prepare-runtime -- --platform linux')
    expect(releaseWorkflow).toContain('--x265-library $x265Library')
    expect(buildHeifSource).toContain("'--target'")
    expect(buildHeifSource).toContain("'heif-info'")
    expect(buildHeifSource).toContain("'heif-dec'")
    expect(buildHeifSource).toContain("'heif-enc'")
    expect(buildHeifSource).toContain("'--parallel'")
    expect(buildHeifSource).toContain('String(buildJobs)')
    expect(releaseWorkflow).toContain('"-DCMAKE_TOOLCHAIN_FILE=$toolchain"')
    expect(releaseWorkflow).toContain('"-DCMAKE_MAKE_PROGRAM=$ninja"')
    expect(releaseWorkflow).toContain('autobuild-2026-08-09-13-03/ffmpeg-n8.1.2-34-g9b6c8969e0-winarm64-gpl-8.1.zip')
    expect(releaseWorkflow).not.toContain('releases/download/latest/ffmpeg-n8.1-latest-winarm64-gpl-8.1.zip')
    expect(releaseWorkflow).toContain('ab350d5e1f77468c98dfe237064efba4004a7b059669fefd206c4a54dd23b211')
    expect(releaseWorkflow).toContain('The downloaded Windows ARM64 FFmpeg checksum does not match.')
    expect(releaseWorkflow.match(/Restore .* native runtime cache/g)).toHaveLength(5)
    expect(releaseWorkflow.match(/Verify cached .* native runtimes/g)).toHaveLength(5)
    expect(releaseWorkflow).toContain('key: vcpkg-windows-x64-v1-${{ env.LIBHEIF_VERSION }}')
    expect(releaseWorkflow).toContain('key: vcpkg-windows-arm64-v1-${{ env.LIBHEIF_VERSION }}')
    expect(releaseWorkflow).not.toContain("hashFiles('.github/workflows/release.yml')")
    expect(releaseWorkflow.match(/curl\.exe --fail --location --retry 3 --retry-all-errors/g)).toHaveLength(2)
    expect(releaseWorkflow.match(/curl --fail --location --retry 5 --retry-all-errors --connect-timeout 30/g)).toHaveLength(2)
    expect(releaseWorkflow).toContain('--bindir="$install_dir/bin"')
    expect(releaseWorkflow).not.toContain('Invoke-WebRequest -Uri $env:FFMPEG_WIN64_URL -OutFile $ffmpegArchive')
    expect(releaseWorkflow).not.toContain('Invoke-WebRequest -Uri $ffmpegUrl -OutFile $ffmpegArchive')
    expect(releaseWorkflow.match(/name: Restore Windows .* FFmpeg archive cache/g)).toHaveLength(2)
    expect(releaseWorkflow.match(/name: Prepare fixed FFmpeg runtime/g)).toHaveLength(2)
    expect(releaseWorkflow.match(/name: Install Windows .* HEIF dependencies/g)).toHaveLength(2)
    expect(releaseWorkflow.match(/\$ffprobeReady = \$null -ne \$ffmpegBinary/g)).toHaveLength(2)
    expect(releaseWorkflow).toContain('"$FFMPEG_LINUX64_URL"')
    expect(releaseWorkflow).toContain("Get-ChildItem -Path $ffmpegRoot -Filter 'ffmpeg.exe' -File -Recurse")
    expect(releaseWorkflow.match(/release:check-architecture/g)).toHaveLength(8)
    expect(packageJson).toContain('release:check-architecture')
  })

  it('gates macOS FFmpeg Mach-O deployment targets before packaging', () => {
    expect(releaseWorkflow).toContain('release:check-macos-ffmpeg')
    expect(releaseWorkflow).toContain('--resource-dir "$GITHUB_WORKSPACE/resources/ffmpeg" --max-minos 12.0')
    expect(packageJson).toContain('release:check-macos-ffmpeg')
    expect(macosFfmpegRuntime).toContain("commandRunner('file'")
    expect(macosFfmpegRuntime).toContain("commandRunner('otool', ['-l'")
    expect(macosFfmpegRuntime).toContain("commandRunner(binaryPath, ['-version']")
    expect(macosFfmpegRuntime).toContain('maximum allowed is ${maxMinos}')
  })

  it('builds macOS native runtimes with an explicit deployment target', () => {
    expect(releaseWorkflow).toContain("MACOSX_DEPLOYMENT_TARGET: '12.0'")
    expect(macosWorkflow).toContain('CSC_KEYCHAIN: signing_temp.keychain')
    expect(macosWorkflow).not.toContain('CSC_LINK: ${{ secrets.MACOS_CSC_LINK }}')
    expect(macosWorkflow).not.toContain('CSC_KEY_PASSWORD: ${{ secrets.MACOS_CSC_KEY_PASSWORD }}')
    expect(macosWorkflow).toContain('uses: apple-actions/import-codesign-certs@v7')
    expect(macosWorkflow).toContain('keychain: signing_temp')
    expect(macosWorkflow).toContain('p12-file-base64: ${{ secrets.MACOS_CSC_LINK }}')
    expect(macosWorkflow).toContain('p12-password: ${{ secrets.MACOS_CSC_KEY_PASSWORD }}')
    expect(macosWorkflow).toContain('name: Notarize macOS app')
    expect(macosWorkflow).toContain('xcrun notarytool submit')
    expect(macosWorkflow).toContain('xcrun notarytool info')
    expect(macosWorkflow).toContain('notarization_attempts=120')
    expect(macosWorkflow).toContain('Apple notarization did not finish within 60 minutes.')
    expect(macosWorkflow).toContain('xcrun stapler staple "$app_path"')
    expect(macosWorkflow).toContain('notarization-info.json')
    expect(macosWorkflow).toContain('brew install cmake ninja pkg-config libde265 kvazaar jpeg-turbo')
    expect(macosWorkflow).toContain('name: Restore macOS FFmpeg build cache')
    expect(macosWorkflow).toContain('path: ${{ runner.temp }}/ffmpeg-install')
    expect(macosWorkflow).toContain('ffmpeg-runtime-macos-${{ runner.arch }}-${{ env.FFMPEG_MACOS_CACHE_VERSION }}')
    expect(macosWorkflow).toContain('Using cached macOS FFmpeg runtime')
    expect(macosWorkflow).toContain('--generator Ninja')
    expect(macosWorkflow).toContain('--jobs "$(sysctl -n hw.ncpu)"')
    expect(macosWorkflow).not.toContain('HOMEBREW_BUILD_FROM_SOURCE')
    expect(macosWorkflow).not.toContain('build_from_source')
    expect(macosWorkflow).not.toMatch(/^\s+x265\s*$/m)
    expect(buildWhisperMacos).toContain('`-DCMAKE_OSX_DEPLOYMENT_TARGET=${deploymentTarget}`')
    expect(buildHeifSource).toContain('`-DCMAKE_OSX_DEPLOYMENT_TARGET=${deploymentTarget}`')
  })

  it('caches repeated Electron and Windows native dependency downloads', () => {
    expect(releaseWorkflow.match(/name: Restore Electron download cache/g)).toHaveLength(5)
    expect(releaseWorkflow).toContain('electron_config_cache: ${{ github.workspace }}/.cache/electron')
    expect(releaseWorkflow).toContain('ELECTRON_BUILDER_CACHE: ${{ github.workspace }}/.cache/electron-builder')
    expect(releaseWorkflow).toContain("VCPKG_BINARY_SOURCES: 'clear;files,C:/vcpkg/binary-cache,readwrite'")
    expect(releaseWorkflow).toContain('VCPKG_DOWNLOADS: C:/vcpkg/downloads')
    expect(releaseWorkflow).toContain('VCPKG_FEATURE_FLAGS: binarycaching')
    expect(releaseWorkflow.match(/name: Restore vcpkg binary cache/g)).toHaveLength(2)
    expect(releaseWorkflow.match(/name: Restore vcpkg source download cache/g)).toHaveLength(2)
    expect(releaseWorkflow).toContain('path: C:/vcpkg/binary-cache')
    expect(releaseWorkflow).toContain('path: C:/vcpkg/downloads')
  })

  it('checks the license manifest before every platform package build', () => {
    expect(releaseWorkflow.match(/npm run check:licenses/g)).toHaveLength(5)
    expect(electronBuilder).toContain('from: LICENSE')
    expect(electronBuilder).toContain('from: docs/THIRD_PARTY_LICENSES.md')
    expect(electronBuilder).toContain('from: resources/runtime-metadata.json')
    expect(electronBuilder).toContain("!node_modules/@huggingface/**")
    expect(electronBuilder).not.toContain('resources/vision/siglip2-base-patch16-224-ONNX')
    expect(electronBuilder).toContain("artifactName: '${productName}-Setup-${version}-${arch}.${ext}'")
    expect(electronBuilder).not.toContain("artifactName: '${productName} Setup ${version} ${arch}.${ext}'")
    expect(electronBuilder).toContain("artifactName: '${name}-${version}-${arch}.${ext}'")
  })

  it('installs the generated Debian package by absolute path in CI', () => {
    expect(releaseWorkflow).toContain('deb_file="$(realpath "$deb_file")"')
    expect(releaseWorkflow).toContain('dpkg-deb -f "$deb_file" Package')
    expect(releaseWorkflow.match(/find release -type f -iname 'aivplayer'/g)).toHaveLength(2)
  })

  it('keeps GitHub artifact selection aligned with the release manifest', () => {
    expect(artifactPolicy).toContain("RELEASE_MANIFEST_NAME = 'release-manifest.json'")
    expect(artifactPolicy).toContain("/^latest(?:-[^/]+)?\\.yml$/i")
    expect(releaseWorkflow).toContain('release/latest*.yml')
    expect(releaseWorkflow).toContain('artifacts/assembled/latest*.yml')
  })

  it('reads back the GitHub release after publishing without write APIs', () => {
    expect(releaseWorkflow).toContain('name: Verify GitHub remote assets')
    expect(releaseWorkflow).toContain('--platform github')
    expect(releaseWorkflow).toContain('remote-verification-github')
    expect(remoteVerification).toContain('sha256File')
    expect(remoteVerification).toContain('Readable.fromWeb')
    expect(remoteVerification).toContain('redirect: \'follow\'')
    expect(remoteVerification).not.toContain("method: 'POST'")
    expect(remoteVerification).not.toContain("method: 'DELETE'")
  })

  it('keeps the release tag, package version and updater metadata tied together', () => {
    expect(releaseVersion).toContain('tag/version mismatch')
    expect(releaseVersion).toContain('Update metadata version mismatch')
    expect(releaseVersion).toContain('references missing artifact')
    expect(releaseVersion).toContain('No electron-updater latest*.yml metadata')
  })

  it('checks each platform package set before uploading artifacts', () => {
    expect(releaseWorkflow.match(/release:check-platform/g)).toHaveLength(5)
    expect(releaseWorkflow).toContain('--platform macos --artifacts-dir release')
    expect(releaseWorkflow).toContain('--platform windows --architecture x64 --artifacts-dir release')
    expect(releaseWorkflow).toContain('--platform windows --architecture arm64 --artifacts-dir release')
    expect(releaseWorkflow).toContain('--platform linux --architecture x64 --artifacts-dir release')
    expect(releaseWorkflow).toContain('--platform linux --architecture arm64 --artifacts-dir release')
    expect(releaseWorkflow).toContain('name: Verify assembled package formats')
    expect(releaseWorkflow).not.toContain('--artifacts-dir artifacts/assembled --report-path artifacts/assembled/platform-release-report-')
    expect(platformRelease).toContain("packages: ['.dmg', '.zip']")
    expect(platformRelease).toContain("packages: ['.AppImage', '.deb', '.snap']")
    expect(platformRelease).toContain('unexpected packages')
  })

  it('retains one hash report per build runner without publishing reports as release assets', () => {
    expect(releaseWorkflow).toContain('release-evidence-macos')
    expect(releaseWorkflow).toContain('release-evidence-windows')
    expect(releaseWorkflow).toContain('release-evidence-windows-arm64')
    expect(releaseWorkflow).toContain('release-evidence-linux')
    expect(releaseWorkflow).toContain('release-evidence-linux-arm64')
    expect(releaseWorkflow).toContain('platform-release-report-macos.json')
    expect(releaseWorkflow).toContain('platform-release-report-windows.json')
    expect(releaseWorkflow).toContain('platform-release-report-linux.json')
    expect(platformRelease).toContain('sha256File')
    expect(platformRelease).toContain('reportPath')
    expect(platformRelease).toContain('duplicate names')
  })

  it('verifies evidence after artifact merge and before version / manifest checks', () => {
    expect(releaseWorkflow).toContain('release:check-evidence')
    expect(releaseWorkflow).toContain('--report-path artifacts/assembled/merged-platform-evidence.json')
    expect(releaseWorkflow).toContain('name: release-evidence-merged')
    expect(releaseWorkflow.indexOf('release:check-evidence')).toBeLessThan(releaseWorkflow.indexOf('release:check-version'))
    expect(platformEvidence).toContain('Missing platform evidence report')
    expect(platformEvidence).toContain('Merged release evidence SHA-256 changed')
    expect(platformEvidence).toContain('reports overlap on artifact')
  })

  it('checks package format signatures before uploading artifacts', () => {
    expect(releaseWorkflow.match(/release:check-formats/g)).toHaveLength(8)
    expect(packageFormats).toContain("case '.dmg':")
    expect(packageFormats).not.toContain("case '.pkg':")
    expect(packageFormats).toContain("case '.exe':")
    expect(packageFormats).toContain("case '.deb':")
    expect(packageFormats).toContain("case '.appimage':")
  })

  it('keeps the local release dry-run offline and separate from remote publishing', () => {
    expect(packageJson).toContain('"release:dry-run"')
    expect(releaseDryRun).not.toContain('verify-remote-release')
    expect(releaseDryRun).not.toContain('fetch(')
    expect(releaseDryRun).toContain('checkPlatformEvidence')
    expect(releaseDryRun).toContain('verifyReleaseManifest')
  })
})
