import { describe, expect, it } from 'vitest'
import { readSource } from './test-source-utils'

describe('subtitle display source constraints', () => {
  it('feeds app subtitle settings into the subtitle overlay', () => {
    const appSource = `${readSource('src/renderer/src/app/player-stage.tsx')}\n${readSource('src/renderer/src/app/use-settings-actions.ts')}`
    const overlaySource = readSource('src/renderer/src/subtitle-overlay.tsx')
    const controlsSource = readSource('src/renderer/src/app/subtitle-display-controls.tsx')

    expect(appSource).toContain('settings={app.appSettings.subtitles}')
    expect(appSource).toContain('const patchSubtitleDisplaySettings')
    expect(appSource).toContain('onSettingsChange={app.patchSubtitleDisplaySettings}')
    expect(appSource).toContain('onResetSettings={app.resetSubtitleDisplaySettings}')
    expect(overlaySource).toContain('SubtitleDisplayControls')
    expect(controlsSource).toContain('effectiveDisplayMode')
    expect(overlaySource).toContain('--subtitle-font-size')
    expect(overlaySource).toContain('--subtitle-line-height')
  })

  it('wires translated subtitle results into the overlay and ASR panel', () => {
    const appSource = `${readSource('src/renderer/src/app/use-subtitle-derived.ts')}\n${readSource('src/renderer/src/app/use-settings-actions.ts')}\n${readSource('src/renderer/src/app/use-subtitle-translation.ts')}\n${readSource('src/renderer/src/app/use-quick-subtitle-action.ts')}\n${readSource('src/renderer/src/app/use-subtitle-cache-effects.ts')}\n${readSource('src/renderer/src/app/use-subtitle-file-actions.ts')}\n${readSource('src/renderer/src/app/subtitle-tools-card.tsx')}\n${readSource('src/renderer/src/app/subtitle-actions-menu.tsx')}\n${readSource('src/renderer/src/app/subtitle-result-summary.tsx')}\n${readSource('src/renderer/src/app/app-overlays.tsx')}\n${readSource('src/renderer/src/app/player-stage.tsx')}`
    const i18nSource = readSource('src/shared/i18n.ts')
    const preloadSource = readSource('src/preload/index.ts')
    const ipcSource = readSource('src/shared/ipc-channels.ts')
    const mediaTypesSource = readSource('src/shared/asr-types.ts')

    expect(ipcSource).toContain('ASR_TRANSLATE_SUBTITLE')
    expect(ipcSource).toContain('ASR_CANCEL_TRANSLATION')
    expect(ipcSource).toContain('ASR_TEST_TRANSLATION_SERVICE')
    expect(ipcSource).toContain('ASR_RESOLVE_TRANSLATED_SUBTITLE_CACHE')
    expect(preloadSource).toContain('translateAsrSubtitle')
    expect(preloadSource).toContain('cancelAsrTranslation')
    expect(preloadSource).toContain('testAsrTranslationService')
    expect(preloadSource).toContain('resolveTranslatedAsrSubtitleCache')
    expect(mediaTypesSource).toContain('AsrSubtitleTranslationRequest')
    expect(mediaTypesSource).toContain('AsrSubtitleTranslationResult')
    expect(mediaTypesSource).toContain('AsrTranslationServiceTestRequest')
    expect(mediaTypesSource).toContain('AsrTranslationServiceTestResult')
    expect(mediaTypesSource).toContain('subtitleLanguage?: string')
    expect(mediaTypesSource).toContain('sourceLanguage?: string')
    expect(mediaTypesSource).toContain('targetLanguage?: SubtitleTargetLanguageId')
    expect(mediaTypesSource).toContain('translationModel?: string')
    expect(mediaTypesSource).toContain('translationBaseUrlSummary?: string')
    expect(mediaTypesSource).toContain('sampleSourceText?: string')
    expect(mediaTypesSource).toContain('sampleTranslatedText?: string')
    expect(appSource).toContain('Languages')
    expect(appSource).toContain('translatedSubtitleResult')
    expect(appSource).toContain('window.aiv.translateAsrSubtitle')
    expect(appSource).toContain('window.aiv.cancelAsrTranslation')
    expect(appSource).toContain('window.aiv.resolveTranslatedAsrSubtitleCache')
    expect(appSource).toContain('translationPath={app.translatedSubtitleResult?.subtitlePath ?? null}')
    expect(appSource).toContain('setTranslatedSubtitleResult')
    expect(appSource).toContain('formatSubtitleLanguageLabel')
    expect(appSource).toContain('const subtitleSourceLanguage =')
    expect(appSource).toContain('const subtitleSourceLanguageLabel =')
    expect(appSource).toContain('const subtitleTranslationSourceLanguage =')
    expect(appSource).toContain('const subtitleTranslationModel =')
    expect(appSource).toContain('const subtitleTranslationModelLabel =')
    expect(appSource).toContain('const subtitleLanguagePairLabel =')
    expect(appSource).toContain('const translatedSubtitleReadyLabel =')
    expect(appSource).toContain('translationServiceTestMessage')
    expect(appSource).toContain('isTestingTranslationService')
    expect(appSource).toContain('subtitleResult?.subtitleLanguage')
    expect(appSource).toContain('sourceLanguage: derived.subtitleTranslationSourceLanguage')
    expect(appSource).toContain('app.copy.asrPanel.translationLanguagePair')
    expect(appSource).toContain('app.copy.asrPanel.translationTargetLanguage')
    expect(appSource).toContain('subtitleTargetLanguageIds')
    expect(appSource).toContain('patchDisplay({ targetLanguage })')
    expect(appSource).toContain('subtitle-target-language-group')
    expect(appSource).toContain('app.copy.asrPanel.translationModel')
    expect(appSource).toContain('app.copy.asrPanel.translationServiceStatus')
    expect(appSource).toContain('app.copy.asrPanel.cancelTranslation')
    expect(appSource).toContain('app.copy.asrPanel.translationElapsed')
    expect(appSource).toContain('app.copy.asrPanel.translationStats')
    expect(appSource).toContain('app.copy.asrPanel.subtitleGenerationElapsed')
    expect(appSource).toContain('generationStats')
    expect(appSource).toContain('app.copy.asrPanel.translationCacheHit')
    expect(appSource).toContain("stage: 'translating'")
    expect(appSource).toContain('translationServiceStatusTone')
    expect(appSource).toContain('copy.asrPanel.translatedSubtitleReady')
    expect(appSource).toContain('openTranslatedSubtitleSrtFile')
    expect(appSource).toContain('className="subtitle-language-row"')
    expect(appSource).toContain('className="subtitle-translation-row"')
    expect(appSource).toContain('window.aiv.testAsrTranslationService')
    expect(appSource).toContain('onTestTranslationService={app.testTranslationService}')
    expect(appSource).toContain('translationServiceTestMessage={app.translationServiceTestMessage}')
    expect(appSource).toContain('isTestingTranslationService={app.isTestingTranslationService}')
    expect(appSource).toContain('matchesCurrentContext')
    expect(appSource).toContain('resolveTranslatedAsrSubtitleCache')
    expect(i18nSource).toContain("translationModel: '翻译模型'")
    expect(i18nSource).toContain("translationModel: 'Translation model'")
    expect(i18nSource).toContain("translationModel: '翻訳モデル'")
    expect(i18nSource).toContain("translationModel: '번역 모델'")
    expect(i18nSource).toContain("translationServiceStatus: '服务状态'")
    expect(i18nSource).toContain("translationServiceStatus: 'Service status'")
    expect(i18nSource).toContain("translationServiceStatus: 'サービス状態'")
    expect(i18nSource).toContain("translationServiceStatus: '서비스 상태'")
    expect(i18nSource).toContain("translationTargetLanguage: '目标语言'")
    expect(i18nSource).toContain("translationTargetLanguage: 'Target language'")
    expect(i18nSource).toContain("translationTargetLanguage: '翻訳先'")
    expect(i18nSource).toContain("translationTargetLanguage: '번역 대상'")
  })

  it('shows button groups for line height and display mode controls', () => {
    const controlsSource = readSource('src/renderer/src/app/subtitle-display-controls.tsx')

    expect(controlsSource).toContain('subtitle-display-choice-group')
    expect(controlsSource).toContain('subtitle-display-choice')
    expect(controlsSource).toContain('effectiveDisplayMode')
    expect(controlsSource).toContain('isDisabled = !hasTranslation && displayMode !== \'source\'')
    expect(controlsSource).toContain('aria-pressed={isSelected}')
    expect(controlsSource).toContain('onChange({ lineHeight })')
    expect(controlsSource).toContain('onChange({ displayMode })')
    expect(controlsSource).toContain('{!hasTranslation ? (')
  })

  it('offers one-tap subtitle font size presets alongside the stepper', () => {
    const controlsSource = readSource('src/renderer/src/app/subtitle-display-controls.tsx')
    const playerCss = readSource('src/renderer/src/styles/player.css')

    expect(controlsSource).toContain('subtitleFontSizePresets')
    expect(controlsSource).toContain('subtitle-display-preset-group')
    expect(controlsSource).toContain('subtitle-display-preset')
    expect(controlsSource).toContain('aria-pressed={isActive}')
    expect(controlsSource).toContain('setFontSize(fontSizePx)')
    expect(playerCss).toContain('.subtitle-display-preset-group')
    expect(playerCss).toContain('.subtitle-display-preset.active')
    expect(playerCss).toContain('.subtitle-display-font-size-controls')
  })

  it('does not use menu roles for form-based quick controls', () => {
    const controlsSource = readSource('src/renderer/src/app/subtitle-display-controls.tsx')

    expect(controlsSource).toContain('className="subtitle-display-controls-menu"')
    expect(controlsSource).not.toContain('className="subtitle-display-controls-menu" role="menu"')
  })

  it('uses css variables for subtitle text sizing', () => {
    const playerCss = readSource('src/renderer/src/styles/player.css')

    expect(playerCss).toMatch(/\.subtitle-text\s*\{[^}]*font-size:\s*var\(--subtitle-font-size\);/s)
    expect(playerCss).toMatch(/\.subtitle-text\s*\{[^}]*line-height:\s*var\(--subtitle-line-height\);/s)
    expect(playerCss).not.toMatch(/\.subtitle-text\s*\{[^}]*font-size:\s*14px;/s)
  })

  it('keeps the quick subtitle controls out of normal document flow', () => {
    const playerCss = readSource('src/renderer/src/styles/player.css')

    expect(playerCss).toContain('.subtitle-display-controls-menu')
    expect(playerCss).toMatch(/\.subtitle-display-controls-menu\s*\{[^}]*position:\s*absolute;/s)
  })

  it('styles the subtitle language status as a compact inline pill', () => {
    const playerCss = readSource('src/renderer/src/styles/player.css')

    expect(playerCss).toContain('.subtitle-language-row')
    expect(playerCss).toContain('.subtitle-translation-row')
    expect(playerCss).toMatch(/\.subtitle-language-row,\s*\.subtitle-translation-row\s*\{[^}]*display:\s*inline-flex;/s)
    expect(playerCss).toMatch(/\.subtitle-language-row,\s*\.subtitle-translation-row\s*\{[^}]*border-radius:\s*var\(--radius-sm\);/s)
    expect(playerCss).toMatch(/\.subtitle-tools-row\s*\{[^}]*flex-wrap:\s*wrap;/s)
  })

  it('styles the subtitle choice buttons like compact segmented controls', () => {
    const playerCss = readSource('src/renderer/src/styles/player.css')

    expect(playerCss).toContain('.subtitle-display-choice-group')
    expect(playerCss).toContain('.subtitle-display-choice')
    expect(playerCss).toContain('.subtitle-display-choice.is-selected')
    expect(playerCss).toContain('.subtitle-display-choice:disabled')
    expect(playerCss).toMatch(/\.subtitle-display-choice-group\s*\{[^}]*display:\s*flex;/s)
    expect(playerCss).toMatch(/\.subtitle-display-choice\s*\{[^}]*white-space:\s*nowrap;/s)
  })
})
