import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const projectRoot = process.cwd()

describe('vision clip collection batch tags wiring', () => {
  it('keeps one normalized tag update behind shared IPC, desktop and preload', () => {
    const channels = readFileSync(join(projectRoot, 'src/shared/ipc-channels.ts'), 'utf8')
    const desktop = readFileSync(join(projectRoot, 'src/desktop/ipc-vision.ts'), 'utf8')
    const preload = readFileSync(join(projectRoot, 'src/preload/index.ts'), 'utf8')
    const store = readFileSync(join(projectRoot, 'src/core/ai/clip-inbox-store.ts'), 'utf8')

    expect(channels).toContain("VISION_CLIP_COLLECTION_BATCH_TAGS: 'vision:clip-collection-batch-tags'")
    expect(channels).toContain("VISION_CLIP_COLLECTION_TAG_CLEANUP: 'vision:clip-collection-tag-cleanup'")
    expect(channels).toContain("VISION_CLIP_COLLECTION_TAG_RENAME: 'vision:clip-collection-tag-rename'")
    expect(channels).toContain("VISION_CLIP_COLLECTION_TAG_METADATA_LIST: 'vision:clip-collection-tag-metadata-list'")
    expect(channels).toContain("VISION_CLIP_COLLECTION_TAG_METADATA_UPDATE: 'vision:clip-collection-tag-metadata-update'")
    expect(channels).toContain("VISION_CLIP_COLLECTION_TAG_OPERATION_HISTORY: 'vision:clip-collection-tag-operation-history'")
    expect(channels).toContain("VISION_CLIP_COLLECTION_TAG_OPERATION_HISTORY_LIST: 'vision:clip-collection-tag-operation-history-list'")
    expect(channels).toContain("VISION_CLIP_COLLECTION_TAG_OPERATION_HISTORY_PAGE: 'vision:clip-collection-tag-operation-history-page'")
    expect(channels).toContain("VISION_CLIP_COLLECTION_TAG_OPERATION_HISTORY_DETAIL: 'vision:clip-collection-tag-operation-history-detail'")
    expect(channels).toContain("VISION_CLIP_COLLECTION_TAG_OPERATION_REDO_HISTORY: 'vision:clip-collection-tag-operation-redo-history'")
    expect(channels).toContain("VISION_CLIP_COLLECTION_TAG_OPERATION_UNDO: 'vision:clip-collection-tag-operation-undo'")
    expect(channels).toContain("VISION_CLIP_COLLECTION_TAG_OPERATION_REDO: 'vision:clip-collection-tag-operation-redo'")
    expect(desktop).toContain('IPC_CHANNELS.VISION_CLIP_COLLECTION_BATCH_TAGS')
    expect(desktop).toContain('getClipInboxStore().updateCollectionsTags(collectionIds, tags, mode)')
    expect(desktop).toContain('normalizeVisionCollectionTags(request?.tags)')
    expect(desktop).toContain('normalizeVisionCollectionTagsMode(request?.mode)')
    expect(preload).toContain('updateVisionClipCollectionsTags')
    expect(preload).toContain('IPC_CHANNELS.VISION_CLIP_COLLECTION_BATCH_TAGS')
    expect(desktop).toContain('IPC_CHANNELS.VISION_CLIP_COLLECTION_TAG_CLEANUP')
    expect(desktop).toContain('getClipInboxStore().removeTagFromAllCollections(tag)')
    expect(preload).toContain('cleanupVisionClipCollectionTag')
    expect(preload).toContain('IPC_CHANNELS.VISION_CLIP_COLLECTION_TAG_CLEANUP')
    expect(desktop).toContain('IPC_CHANNELS.VISION_CLIP_COLLECTION_TAG_RENAME')
    expect(desktop).toContain('getClipInboxStore().renameTagAcrossCollections(fromTag, toTag)')
    expect(preload).toContain('renameVisionClipCollectionTag')
    expect(preload).toContain('IPC_CHANNELS.VISION_CLIP_COLLECTION_TAG_RENAME')
    expect(desktop).toContain('IPC_CHANNELS.VISION_CLIP_COLLECTION_TAG_METADATA_LIST')
    expect(desktop).toContain('getClipInboxStore().listTagMetadata()')
    expect(desktop).toContain('IPC_CHANNELS.VISION_CLIP_COLLECTION_TAG_METADATA_UPDATE')
    expect(desktop).toContain('getClipInboxStore().saveTagMetadata(request)')
    expect(desktop).toContain('wouldCreateVisionCollectionTagParentCycle')
    expect(preload).toContain('listVisionClipCollectionTagMetadata')
    expect(preload).toContain('updateVisionClipCollectionTagMetadata')
    expect(desktop).toContain('getClipInboxStore().getLastTagOperation()')
    expect(desktop).toContain('getClipInboxStore().listTagOperationHistory()')
    expect(desktop).toContain('getClipInboxStore().listTagOperationHistoryPage(request)')
    expect(desktop).toContain('getClipInboxStore().getTagOperationHistoryDetail(operationId)')
    expect(desktop).toContain('getClipInboxStore().getLastTagRedoOperation()')
    expect(desktop).toContain('getClipInboxStore().undoLastTagOperation()')
    expect(desktop).toContain('getClipInboxStore().redoLastTagOperation()')
    expect(preload).toContain('getVisionClipCollectionTagOperationHistory')
    expect(preload).toContain('listVisionClipCollectionTagOperationHistory')
    expect(preload).toContain('listVisionClipCollectionTagOperationHistoryPage')
    expect(preload).toContain('getVisionClipCollectionTagOperationHistoryDetail')
    expect(preload).toContain('getVisionClipCollectionTagOperationRedoHistory')
    expect(preload).toContain('undoVisionClipCollectionTagOperation')
    expect(preload).toContain('redoVisionClipCollectionTagOperation')
    expect(store).toContain('updateCollectionsTags(collectionIds: readonly string[], tags: unknown, mode: unknown = \'replace\')')
    expect(store).toContain('UPDATE clip_collections SET tags_json = ?, updated_at = ? WHERE id = ?')
    expect(store).toContain('renameTagAcrossCollections(fromTag: unknown, toTag: unknown)')
    expect(store).toContain('CREATE TABLE IF NOT EXISTS clip_tag_metadata')
    expect(store).toContain('note TEXT NOT NULL DEFAULT')
    expect(store).toContain('is_favorite INTEGER NOT NULL DEFAULT 0')
    expect(store).toContain('ensureTagMetadataColumn')
    expect(store).toContain('saveTagMetadata(input: VisionClipCollectionTagMetadataUpdateRequest)')
    expect(store).toContain('wouldCreateVisionCollectionTagParentCycle')
    expect(store).toContain('clip_tag_operation_history')
    expect(store).toContain('undoLastTagOperation()')
    expect(store).toContain('getLastTagRedoOperation()')
    expect(store).toContain('redoLastTagOperation()')
    expect(store).toContain("recordTagOperation('batch'")
  })
})
