import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const projectRoot = process.cwd()

describe('vision clip collection operation wiring', () => {
  it('keeps collection updates and undo/redo behind shared IPC, desktop and preload', () => {
    const channels = readFileSync(join(projectRoot, 'src/shared/ipc-channels.ts'), 'utf8')
    const desktop = readFileSync(join(projectRoot, 'src/desktop/ipc-vision.ts'), 'utf8')
    const preload = readFileSync(join(projectRoot, 'src/preload/index.ts'), 'utf8')
    const store = readFileSync(join(projectRoot, 'src/core/ai/clip-inbox-store.ts'), 'utf8')

    expect(channels).toContain("VISION_CLIP_COLLECTION_FLAGS_UPDATE: 'vision:clip-collection-flags-update'")
    expect(channels).toContain("VISION_CLIP_COLLECTION_OPERATION_HISTORY: 'vision:clip-collection-operation-history'")
    expect(channels).toContain("VISION_CLIP_COLLECTION_OPERATION_HISTORY_LIST: 'vision:clip-collection-operation-history-list'")
    expect(channels).toContain("VISION_CLIP_COLLECTION_OPERATION_HISTORY_DETAIL: 'vision:clip-collection-operation-history-detail'")
    expect(channels).toContain("VISION_CLIP_COLLECTION_OPERATION_REDO_HISTORY: 'vision:clip-collection-operation-redo-history'")
    expect(channels).toContain("VISION_CLIP_COLLECTION_OPERATION_UNDO: 'vision:clip-collection-operation-undo'")
    expect(channels).toContain("VISION_CLIP_COLLECTION_OPERATION_REDO: 'vision:clip-collection-operation-redo'")
    expect(channels).toContain("VISION_CLIP_COLLECTION_OPERATION_BATCH_UNDO: 'vision:clip-collection-operation-batch-undo'")
    expect(channels).toContain("VISION_CLIP_COLLECTION_OPERATION_BATCH_REDO: 'vision:clip-collection-operation-batch-redo'")
    expect(desktop).toContain('IPC_CHANNELS.VISION_CLIP_COLLECTION_FLAGS_UPDATE')
    expect(desktop).toContain('getClipInboxStore().updateCollectionFlags')
    expect(desktop).toContain('IPC_CHANNELS.VISION_CLIP_COLLECTION_OPERATION_HISTORY')
    expect(desktop).toContain('getClipInboxStore().getLastCollectionOperation()')
    expect(desktop).toContain('IPC_CHANNELS.VISION_CLIP_COLLECTION_OPERATION_HISTORY_LIST')
    expect(desktop).toContain('getClipInboxStore().listCollectionOperationHistory()')
    expect(desktop).toContain('IPC_CHANNELS.VISION_CLIP_COLLECTION_OPERATION_HISTORY_DETAIL')
    expect(desktop).toContain('getClipInboxStore().getCollectionOperationHistoryDetail(operationId)')
    expect(desktop).toContain('IPC_CHANNELS.VISION_CLIP_COLLECTION_OPERATION_REDO_HISTORY')
    expect(desktop).toContain('getClipInboxStore().getLastCollectionRedoOperation()')
    expect(desktop).toContain('IPC_CHANNELS.VISION_CLIP_COLLECTION_OPERATION_UNDO')
    expect(desktop).toContain('getClipInboxStore().undoCollectionOperation(operationId)')
    expect(desktop).toContain('IPC_CHANNELS.VISION_CLIP_COLLECTION_OPERATION_REDO')
    expect(desktop).toContain('getClipInboxStore().redoCollectionOperation(operationId)')
    expect(desktop).toContain('IPC_CHANNELS.VISION_CLIP_COLLECTION_OPERATION_BATCH_UNDO')
    expect(desktop).toContain('getClipInboxStore().undoCollectionOperations(operationIds')
    expect(desktop).toContain('IPC_CHANNELS.VISION_CLIP_COLLECTION_OPERATION_BATCH_REDO')
    expect(desktop).toContain('getClipInboxStore().redoCollectionOperations(operationIds')
    expect(preload).toContain('updateVisionClipCollectionFlags')
    expect(preload).toContain('IPC_CHANNELS.VISION_CLIP_COLLECTION_FLAGS_UPDATE')
    expect(preload).toContain('getVisionClipCollectionOperationHistory')
    expect(preload).toContain('listVisionClipCollectionOperationHistory')
    expect(preload).toContain('getVisionClipCollectionOperationHistoryDetail')
    expect(preload).toContain('getVisionClipCollectionOperationRedoHistory')
    expect(preload).toContain('undoVisionClipCollectionOperation: (operationId?: string)')
    expect(preload).toContain('redoVisionClipCollectionOperation: (operationId?: string)')
    expect(preload).toContain('undoVisionClipCollectionOperations: (operationIds: string[])')
    expect(preload).toContain('redoVisionClipCollectionOperations: (operationIds: string[])')
    expect(preload).toContain('IPC_CHANNELS.VISION_CLIP_COLLECTION_OPERATION_REDO')
    expect(store).toContain('CREATE TABLE IF NOT EXISTS clip_collection_operation_history')
    expect(store).toContain('updateCollectionFlags(request: VisionClipCollectionFlagUpdateRequest)')
    expect(store).toContain('recordCollectionOperation(\'flags\'')
    expect(store).toContain('recordCollectionOperation(\'merge\'')
    expect(store).toContain('undoLastCollectionOperation()')
    expect(store).toContain('getLastCollectionRedoOperation()')
    expect(store).toContain('redoLastCollectionOperation()')
    expect(store).toContain('undoCollectionOperations(operationIds')
    expect(store).toContain('redoCollectionOperations(operationIds')
  })
})
