import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { VISION_FRAME_INTERVAL_SECONDS, VISION_MODEL_ID, VISION_MODEL_VARIANT, VISION_SEARCH_FULL_EXPORT_MAX_RESULTS, VISION_VECTOR_DISTANCE_TYPE, VISION_VECTOR_INDEX_MIN_ROWS, VISION_VECTOR_INDEX_TYPE } from '../../src/shared/vision-types'
import { getVisionModelPaths } from '../../src/core/ai/vision-model'
import { calculateVisionLexicalMatch, combineVisionHybridScore, filterVisionSearchResultsByEvidenceTypes, getVisionSearchResultKey } from '../../src/core/ai/vision-search'
import { dotProduct } from '../../src/core/ai/vision-library'

const projectRoot = process.cwd()

describe('vision library setup', () => {
  it('reads both JavaScript arrays and LanceDB Arrow vectors', () => {
    const arrowVector = { length: 3, get: (index: number) => [0.2, 0.3, 0.5][index] }

    expect(dotProduct([1, 2, 3], [4, 5, 6])).toBe(32)
    expect(dotProduct(arrowVector, [1, 2, 3])).toBeCloseTo(2.3)
  })

  it('uses the checked-in model layout and the expected frame interval', () => {
    const paths = getVisionModelPaths(join(projectRoot, 'resources'))

    expect(VISION_MODEL_ID).toBe('siglip2-base-patch16-224-ONNX')
    expect(VISION_MODEL_VARIANT).toBe('uint8')
    expect(VISION_FRAME_INTERVAL_SECONDS).toBe(3)
    expect(VISION_VECTOR_DISTANCE_TYPE).toBe('dot')
    expect(VISION_VECTOR_INDEX_TYPE).toBe('IVF_FLAT')
    expect(VISION_VECTOR_INDEX_MIN_ROWS).toBe(10_000)
    expect(VISION_SEARCH_FULL_EXPORT_MAX_RESULTS).toBe(1_000_000)
    expect(paths.combinedModelPath.endsWith('onnx/model_uint8.onnx')).toBe(true)
    expect(paths.textModelPath.endsWith('onnx/text_model_uint8.onnx')).toBe(true)
    expect(paths.visionModelPath.endsWith('onnx/vision_model_uint8.onnx')).toBe(true)
  })

  it('keeps the local model files available for development', () => {
    const paths = getVisionModelPaths(join(projectRoot, 'resources'))
    expect(existsSync(paths.combinedModelPath)).toBe(true)
    expect(existsSync(paths.textModelPath)).toBe(true)
    expect(existsSync(paths.visionModelPath)).toBe(true)
  })

  it('exposes the visual search IPC surface', () => {
    const source = readFileSync(join(projectRoot, 'src/desktop/ipc-vision.ts'), 'utf8')
    expect(source).toContain('VISION_INDEX_START')
    expect(source).toContain('VISION_INDEX_CANCEL')
    expect(source).toContain('VISION_SEARCH_TEXT')
    expect(source).toContain('VISION_SEARCH_IMAGE')
    expect(source).toContain('VISION_SEARCH_PAGE')
    expect(source).toContain('VISION_SEARCH_FULL_EXPORT')
    expect(source).toContain('VISION_SEARCH_FULL_EXPORT_CANCEL')
    expect(source).toContain('VISION_SEARCH_FULL_EXPORT_RETRY')
    expect(source).toContain('VISION_SEARCH_FULL_EXPORT_RECREATE')
    expect(source).toContain('VISION_SEARCH_FULL_EXPORT_BATCH_RECREATE')
    expect(source).toContain('recreatedTaskId')
    expect(source).toContain('runVisionSearchFullExportTask')
    expect(source).toContain('writeVisionSearchResultsExportResumable')
    expect(source).toContain('acquireVisionSearchExportOutputLock')
    expect(source).toContain('withVisionSearchExportOutputLock')
    expect(source).toContain('searchResultsFullExportOutputLocked')
    expect(source).toContain('resumeVisionSearchExports')
    expect(source).toContain('getVisionSearchExportStore')
    expect(source).toContain('getSearchRevision')
    expect(source).toContain('isVisionSearchRevisionUnavailableError')
    expect(source).toContain('searchResultsFullExportRevisionUnavailable')
    expect(source).toContain('getVisionSearchRevisionWithCatalogs')
    expect(source).toContain('VisionSearchCatalogSnapshot')
    expect(source).toContain('getVisionEntityCatalogSearchQueries')
    expect(source).toContain('getSpeakerDiarizationCatalogSearchQueries')
    expect(source).toContain('applyVisionEntityCatalogToResults')
    expect(source).toContain('applySpeakerDiarizationCatalogToResults')
    expect(source).toContain('searchRevision')
    expect(source).toContain('VisionSearchCursorStore')
    expect(source).toContain('searchVisionResultPage')
    expect(source).toContain('searchVisionFullResults')
    expect(source).toContain('VISION_SEARCH_RESULTS_EXPORT')
    expect(source).toContain('renderVisionSearchResultsExport')
    expect(source).toContain('filterSpeakerDiarizationCatalogSearchResults')
    expect(source).toContain('scopedSpeakerGroups')
    expect(source).toContain('normalizeVisionObjectDetectionFilterState')
    expect(source).toContain('objectDetectionFilter')
    expect(source).toContain('VISION_ENTITY_CATALOG_GET')
    expect(source).toContain('VISION_ENTITY_CATALOG_UPDATE')
    expect(source).toContain('VISION_ENTITY_CATALOG_BATCH_UPDATE')
    expect(source).toContain('VISION_SCAN_DIRECTORY_START')
    expect(source).toContain('VISION_SCAN_DIRECTORY_CANCEL')
  })

  it('keeps visual indexing behind an explicit user action', () => {
    const appEffects = readFileSync(join(projectRoot, 'src/renderer/src/app/use-app-effects.ts'), 'utf8')
    const folder = readFileSync(join(projectRoot, 'src/renderer/src/app/use-vision-library-folder.ts'), 'utf8')
    const folderView = readFileSync(join(projectRoot, 'src/renderer/src/app/vision-library-folder.tsx'), 'utf8')
    expect(appEffects).not.toContain('useVisionIndexEffect')
    expect(folder).not.toContain('enqueueVisionIndex')
    expect(folderView).toContain('onStartIndex')
  })

  it('keeps the search-to-editing-project path visible in the renderer source', () => {
    const panel = readFileSync(join(projectRoot, 'src/renderer/src/app/vision-panel.tsx'), 'utf8')
    const actions = readFileSync(join(projectRoot, 'src/renderer/src/app/use-editing-actions.ts'), 'utf8')
    const ipc = readFileSync(join(projectRoot, 'src/desktop/ipc-vision.ts'), 'utf8')
    const preload = readFileSync(join(projectRoot, 'src/preload/index.ts'), 'utf8')
    expect(panel).toContain('selectedResultIds')
    expect(panel).toContain('selectAllSearchResults')
    expect(panel).toContain('clearSearchResultSelection')
    expect(panel).toContain('onSelectAllResults={selectAllSearchResults}')
    expect(panel).toContain('loadMoreSearchResults')
    expect(panel).toContain('hasMoreResults={hasMoreSearchResults}')
    expect(panel).toContain('onFindSimilar={findSimilarResult}')
    expect(panel).toContain('onReturnToSearch={returnToSearchResults}')
    expect(panel).toContain('createVisionSimilarSearchRequest')
    expect(panel).toContain("kind: 'similar'")
    expect(panel).toContain('searchVisionPage(request)')
    expect(panel).toContain('searchCursor')
    expect(panel).toContain('getNextVisionSearchLimit(searchResultLimit)')
    expect(panel).toContain('objectDetectionFilter: context.objectDetectionFilter')
    expect(panel).toContain('savedSearch.objectDetectionFilter')
    expect(panel).toContain('exportVisionSearchResults')
    expect(panel).toContain('exportVisionSearchResultsFull')
    expect(panel).toContain('selectedResultIds.size > 0 ? results.filter')
    expect(panel).toContain('isSimilarSearch={searchContext?.kind === \'similar\'}')
    expect(panel).toContain('createEditingProjectFromVisionResults')
    expect(panel).toContain('onToggleSelection')
    expect(panel).toContain('saveVisionClipCollection')
    expect(panel).toContain('listVisionClipCollections')
    expect(panel).toContain('isMediaFileAvailable')
    expect(panel).toContain('repairCollection')
    expect(panel).toContain('VisionEntityCatalog')
    expect(panel).toContain('updateVisionEntityCatalog')
    expect(panel).toContain('updateVisionEntityCatalogBatch')
    expect(panel).toContain('createVisionEntityCatalog')
    expect(panel).toContain('onBatchRetry')
    expect(panel).toContain('collectionRepairNoMatch')
    expect(panel).toContain('pendingResultSeek')
    expect(panel).toContain('loadedmetadata')
    expect(actions).toContain('getMediaMetadata')
    expect(actions).toContain('createEditingProjectFromVisionSearchResults')
    expect(actions).toContain('setEditingSourceFiles')
    expect(ipc).toContain('VISION_CLIP_COLLECTION_LIST')
    expect(ipc).toContain('VISION_CLIP_COLLECTION_SAVE')
    expect(ipc).toContain('VISION_CLIP_COLLECTION_DELETE')
    expect(preload).toContain('saveVisionClipCollection')
    expect(preload).toContain('getVisionEntityCatalog')
    expect(preload).toContain('updateVisionEntityCatalog')
    expect(preload).toContain('updateVisionEntityCatalogBatch')
    expect(preload).toContain('createVisionEntityCatalog')
    expect(preload).toContain('retryVisionIndexFailures')
    expect(preload).toContain('searchVisionSimilar')
    expect(preload).toContain('searchVisionPage')
    expect(preload).toContain('exportVisionSearchResultsFull')
    expect(preload).toContain('recreateVisionSearchResultsFullExport')
    expect(preload).toContain('recreateVisionSearchResultsFullExports')
    expect(preload).toContain('VisionSearchExportBatchRecreateResult')
    expect(preload).toContain('cancelVisionSearchResultsFullExport')
    expect(preload).toContain('exportVisionSearchResults')
    const resultView = readFileSync(join(projectRoot, 'src/renderer/src/app/vision-search-results.tsx'), 'utf8')
    expect(resultView).toContain('groupVisionSimilarSearchResults')
    expect(resultView).toContain('similarGroupMeta')
    expect(resultView).toContain('onExportResults')
    expect(resultView).toContain('onExportAllResults')
    expect(resultView).toContain('exportSearchResultsAll')
    expect(resultView).toContain('exportSearchResultsJson')
  })

  it('keeps the reusable Clip Inbox Electron smoke wired into npm scripts', () => {
    const packageJson = JSON.parse(readFileSync(join(projectRoot, 'package.json'), 'utf8')) as { scripts?: Record<string, string> }
    const smoke = readFileSync(join(projectRoot, 'scripts/smoke-vision-clip-inbox.ts'), 'utf8')
    expect(packageJson.scripts?.['smoke:vision-clip-inbox']).toContain('smoke-vision-clip-inbox.ts')
    expect(packageJson.scripts?.['smoke:vision-clip-collection-import']).toContain('smoke-vision-clip-collection-import.ts')
    expect(packageJson.scripts?.['smoke:vision-clip-collection-duplicate']).toContain('smoke-vision-clip-collection-duplicate.ts')
    expect(packageJson.scripts?.['smoke:vision-clip-collection-batch-duplicate']).toContain('smoke-vision-clip-collection-batch-duplicate.ts')
    expect(packageJson.scripts?.['smoke:vision-clip-collection-batch-delete']).toContain('smoke-vision-clip-collection-batch-delete.ts')
    expect(packageJson.scripts?.['smoke:vision-clip-collection-batch-rename']).toContain('smoke-vision-clip-collection-batch-rename.ts')
    expect(packageJson.scripts?.['smoke:vision-clip-collection-batch-export']).toContain('smoke-vision-clip-collection-batch-export.ts')
    expect(smoke).toContain('listVisionClipCollections')
    expect(smoke).toContain('editing-timeline')
    expect(smoke).toContain('persistedSelections')
    expect(smoke).toContain('persistedCollection.tags')
    expect(smoke).toContain('vision-collection-missing')
    expect(smoke).toContain('repairCollectionSources')
    const importSmoke = readFileSync(join(projectRoot, 'scripts/smoke-vision-clip-collection-import.ts'), 'utf8')
    expect(importSmoke).toContain('name: \'导入选段集合\'')
    expect(importSmoke).toContain('导入选段集合')
    expect(importSmoke).toContain('newCollectionId')
    const duplicateSmoke = readFileSync(join(projectRoot, 'scripts/smoke-vision-clip-collection-duplicate.ts'), 'utf8')
    expect(duplicateSmoke).toContain("name: '复制集合'")
    expect(duplicateSmoke).toContain('duplicateId')
    expect(duplicateSmoke).toContain('independent: true')
    const batchDuplicateSmoke = readFileSync(join(projectRoot, 'scripts/smoke-vision-clip-collection-batch-duplicate.ts'), 'utf8')
    expect(batchDuplicateSmoke).toContain("name: '复制选中集合'")
    expect(batchDuplicateSmoke).toContain('duplicateCount')
    expect(batchDuplicateSmoke).toContain('independent: true')
    const batchDeleteSmoke = readFileSync(join(projectRoot, 'scripts/smoke-vision-clip-collection-batch-delete.ts'), 'utf8')
    expect(batchDeleteSmoke).toContain("name: '删除选中集合'")
    expect(batchDeleteSmoke).toContain('confirmationCancel: true')
    expect(batchDeleteSmoke).toContain('remainingCount')
    const batchRenameSmoke = readFileSync(join(projectRoot, 'scripts/smoke-vision-clip-collection-batch-rename.ts'), 'utf8')
    expect(batchRenameSmoke).toContain("name: '重命名选中集合'")
    expect(batchRenameSmoke).toContain('metadataPreserved: true')
    expect(batchRenameSmoke).toContain('screenshotPath')
    const inlineRenameSmoke = readFileSync(join(projectRoot, 'scripts/smoke-vision-clip-collection-inline-rename.ts'), 'utf8')
    expect(packageJson.scripts?.['smoke:vision-clip-collection-inline-rename']).toContain('smoke-vision-clip-collection-inline-rename.ts')
    expect(inlineRenameSmoke).toContain('enterSaved: true')
    expect(inlineRenameSmoke).toContain('escapeCancelled: true')
    expect(inlineRenameSmoke).toContain('emptyTitleGuarded: true')
    expect(inlineRenameSmoke).toContain('metadataPreserved: true')
    const inlineTagsSmoke = readFileSync(join(projectRoot, 'scripts/smoke-vision-clip-collection-inline-tags.ts'), 'utf8')
    expect(packageJson.scripts?.['smoke:vision-clip-collection-inline-tags']).toContain('smoke-vision-clip-collection-inline-tags.ts')
    expect(inlineTagsSmoke).toContain('normalized: true')
    expect(inlineTagsSmoke).toContain('escapeCancelled: true')
    expect(inlineTagsSmoke).toContain('cleared: true')
    expect(inlineTagsSmoke).toContain('metadataPreserved: true')
    const batchTagsSmoke = readFileSync(join(projectRoot, 'scripts/smoke-vision-clip-collection-batch-tags.ts'), 'utf8')
    expect(packageJson.scripts?.['smoke:vision-clip-collection-batch-tags']).toContain('smoke-vision-clip-collection-batch-tags.ts')
    expect(batchTagsSmoke).toContain('normalized: true')
    expect(batchTagsSmoke).toContain('appended: true')
    expect(batchTagsSmoke).toContain('cleared: true')
    expect(batchTagsSmoke).toContain('removed: true')
    expect(batchTagsSmoke).toContain('cancelled: true')
    expect(batchTagsSmoke).toContain('metadataPreserved: true')
    const tagManagerSmoke = readFileSync(join(projectRoot, 'scripts/smoke-vision-clip-collection-tag-manager.ts'), 'utf8')
    expect(packageJson.scripts?.['smoke:vision-clip-collection-tag-manager']).toContain('smoke-vision-clip-collection-tag-manager.ts')
    expect(tagManagerSmoke).toContain("cleanedTag: '海边'")
    expect(tagManagerSmoke).toContain('updatedCount: 2')
    expect(tagManagerSmoke).toContain('cancelled: true')
    expect(tagManagerSmoke).toContain('metadataPreserved: true')
    const tagMetadataSmoke = readFileSync(join(projectRoot, 'scripts/smoke-vision-clip-collection-tag-metadata.ts'), 'utf8')
    expect(packageJson.scripts?.['smoke:vision-clip-collection-tag-metadata']).toContain('smoke-vision-clip-collection-tag-metadata.ts')
    expect(tagMetadataSmoke).toContain("styledTag: '海边'")
    expect(tagMetadataSmoke).toContain("parentTag: '采访'")
    expect(tagMetadataSmoke).toContain('colors: true')
    expect(tagMetadataSmoke).toContain('persisted: true')
    expect(tagMetadataSmoke).toContain('screenshotPath')
    const tagUndoSmoke = readFileSync(join(projectRoot, 'scripts/smoke-vision-clip-collection-tag-undo.ts'), 'utf8')
    expect(packageJson.scripts?.['smoke:vision-clip-collection-tag-undo']).toContain('smoke-vision-clip-collection-tag-undo.ts')
    expect(tagUndoSmoke).toContain('cleaned: true')
    expect(tagUndoSmoke).toContain('restored: true')
    expect(tagUndoSmoke).toContain('persistedHistory: true')
    expect(tagUndoSmoke).toContain('metadataUndo: true')
    const tagHierarchySmoke = readFileSync(join(projectRoot, 'scripts/smoke-vision-clip-collection-tag-hierarchy.ts'), 'utf8')
    expect(packageJson.scripts?.['smoke:vision-clip-collection-tag-hierarchy']).toContain('smoke-vision-clip-collection-tag-hierarchy.ts')
    expect(tagHierarchySmoke).toContain("path: '项目 / 访谈 / 海边'")
    expect(tagHierarchySmoke).toContain('cycleRejected: true')
    expect(tagHierarchySmoke).toContain('candidateFiltered: true')
    expect(tagHierarchySmoke).toContain('persisted: true')
    const tagNotesSmoke = readFileSync(join(projectRoot, 'scripts/smoke-vision-clip-collection-tag-notes.ts'), 'utf8')
    expect(packageJson.scripts?.['smoke:vision-clip-collection-tag-notes']).toContain('smoke-vision-clip-collection-tag-notes.ts')
    expect(tagNotesSmoke).toContain('notePersisted: true')
    expect(tagNotesSmoke).toContain('favoritePersisted: true')
    expect(tagNotesSmoke).toContain('tagsUnchanged: true')
    const batchTagUndoSmoke = readFileSync(join(projectRoot, 'scripts/smoke-vision-clip-collection-batch-tag-undo.ts'), 'utf8')
    expect(packageJson.scripts?.['smoke:vision-clip-collection-batch-tag-undo']).toContain('smoke-vision-clip-collection-batch-tag-undo.ts')
    expect(batchTagUndoSmoke).toContain('appendedUndo: true')
    expect(batchTagUndoSmoke).toContain('emptyBatchUndo: true')
    expect(batchTagUndoSmoke).toContain('untouchedPreserved: true')
    expect(batchTagUndoSmoke).toContain('historyExhausted: true')
    const tagRenameSmoke = readFileSync(join(projectRoot, 'scripts/smoke-vision-clip-collection-tag-rename.ts'), 'utf8')
    expect(packageJson.scripts?.['smoke:vision-clip-collection-tag-rename']).toContain('smoke-vision-clip-collection-tag-rename.ts')
    expect(tagRenameSmoke).toContain("renamedFrom: '海边'")
    expect(tagRenameSmoke).toContain("renamedTo: '访谈'")
    expect(tagRenameSmoke).toContain('updatedCount: 2')
    expect(tagRenameSmoke).toContain('merged: true')
    expect(tagRenameSmoke).toContain('cancelled: true')
    expect(tagRenameSmoke).toContain('metadataPreserved: true')
    const filterSmoke = readFileSync(join(projectRoot, 'scripts/smoke-vision-clip-collection-filter.ts'), 'utf8')
    expect(packageJson.scripts?.['smoke:vision-clip-collection-filter']).toContain('smoke-vision-clip-collection-filter.ts')
    expect(filterSmoke).toContain('queryMatches: 2')
    expect(filterSmoke).toContain('tagMatches: 1')
    expect(filterSmoke).toContain('dataUnchanged')
    expect(filterSmoke).toContain('sessionOnly')
    const batchExportSmoke = readFileSync(join(projectRoot, 'scripts/smoke-vision-clip-collection-batch-export.ts'), 'utf8')
    expect(batchExportSmoke).toContain("name: '导出选中集合'")
    expect(batchExportSmoke).toContain('exportVersion')
    expect(batchExportSmoke).toContain('newIds: true')
  })

  it('scores subtitle and filename matches for hybrid retrieval', () => {
    const subtitleMatch = calculateVisionLexicalMatch('红色汽车', '夜晚的红色汽车正在城市道路上行驶', 'demo.mp4')
    const filenameMatch = calculateVisionLexicalMatch('城市夜景', '', '城市夜景-红色汽车.mp4')

    expect(subtitleMatch?.source).toBe('subtitle')
    expect(subtitleMatch?.score).toBeGreaterThan(0.8)
    expect(filenameMatch?.source).toBe('filename')
    expect(filenameMatch?.score).toBeGreaterThan(0.4)
    expect(combineVisionHybridScore(1, 1)).toBe(1)
    expect(combineVisionHybridScore(0, 1)).toBeCloseTo(0.45)
  })

  it('keeps OCR evidence rows distinct when they have no frame id', () => {
    expect(getVisionSearchResultKey({ id: 'ocr-a', evidenceId: 'ocr-a', frameId: '', evidenceType: 'ocr' })).toBe('ocr-a')
    expect(getVisionSearchResultKey({ id: 'frame-a', evidenceId: 'subtitle-a', frameId: 'frame-a', evidenceType: 'subtitle' })).toBe('frame-a')
  })

  it('filters evidence types without collapsing the result identity', () => {
    const result = (id: string, evidenceType: 'subtitle' | 'ocr', score: number) => ({ id, videoPath: '/tmp/demo.mp4', fileName: 'demo.mp4', timestampSeconds: 0, thumbnailPath: '', score, evidenceType, modelId: 'test', modelVariant: 'test' })
    const results = [result('subtitle-1', 'subtitle', 0.9), result('ocr-1', 'ocr', 0.8), result('ocr-2', 'ocr', 0.7)]
    expect(filterVisionSearchResultsByEvidenceTypes(results, ['ocr'], 1).map((result) => result.id)).toEqual(['ocr-1'])
    expect(filterVisionSearchResultsByEvidenceTypes(results, [], 1).map((result) => result.id)).toEqual(['subtitle-1', 'ocr-1', 'ocr-2'])
  })

  it('keeps the incremental manifest and caption tables in the library source', () => {
    const source = readFileSync(join(projectRoot, 'src/core/ai/vision-library.ts'), 'utf8')
    expect(source).toContain("SOURCE_TABLE_NAME = 'video_sources'")
    expect(source).toContain("CAPTION_TABLE_NAME = 'video_captions'")
    expect(source).toContain("SEARCH_DOCUMENT_TABLE_NAME = 'video_search_documents'")
    expect(source).toContain("EVIDENCE_TABLE_NAME = 'video_evidence'")
    expect(source).toContain('VISION_EVIDENCE_SCHEMA')
    expect(source).toContain("new Field('box_xmin'")
    expect(source).toContain('migrateEvidenceTableIfNeeded')
    expect(source).toContain('schema: VISION_EVIDENCE_SCHEMA')
    expect(source).toContain('buildEvidenceRows')
    expect(source).toContain('replaceEvidenceRows')
    expect(source).toContain('createVisionSourceFingerprint')
    expect(source).toContain('preservedRows')
    expect(source).toContain("row.evidence_type !== 'subtitle' && row.evidence_type !== 'visual'")
    expect(source).toContain('async upsertEvidence(evidence: VisionEvidence)')
    expect(source).toContain('async listEvidenceSources(limit?: number, offset?: number, evidenceTypes?: readonly VisionDerivedEvidenceType[])')
    expect(source).toContain('private async clearEvidenceTypes(videoPath: string, evidenceTypes: readonly VisionDerivedEvidenceType[])')
    expect(source).toContain('async clearEvidenceBatch(value: unknown)')
    expect(source).toContain('normalizeVisionEvidenceClearTargets')
    expect(source).toContain('async replaceSpeakerEvidence(videoPath: string, evidence: readonly VisionEvidence[])')
    expect(source).toContain('async replaceObjectEvidenceRows(videoPath: string, evidence: readonly VisionEvidence[])')
    expect(source).toContain("this.replaceEvidenceTypeRows(videoPath, 'speaker'")
    expect(source).toContain('async clearSpeakerEvidence(videoPath: string)')
    expect(source).toContain('async listSpeakerEvidenceSources(limit?: number, offset?: number)')
    expect(source).toContain('async clearSpeakerEvidenceBatch(videoPaths: readonly string[])')
    expect(source).toContain('evidenceCount')
    expect(source).toContain('async listSources(limit?: number, offset?: number)')
    expect(source).toContain('clampSourceOffset')
    expect(source).toContain('.slice(sourceOffset, sourceOffset + sourceLimit)')
    expect(source).toContain('metadata: null')
    expect(source).toContain("await existing.delete(`id = '")
    expect(source).toContain('searchLexicalByEvidence')
    expect(source).toContain('getVisionSearchResultKey')
    expect(source).toContain('lexicalCandidates.length === 0')
    expect(source).toContain('getVisualEvidenceByFrameIds')
    expect(source).toContain('async searchSimilar(request: VisionSimilarSearchRequest)')
    expect(source).toContain('normalizeVisionSimilarSearchRequest')
    expect(source).toContain('searchTextAll')
    expect(source).toContain('searchImageAll')
    expect(source).toContain('searchSimilarAll')
    expect(source).toContain('searchHybridAll')
    expect(source).toContain('VISION_SEARCH_FULL_EXPORT_MAX_RESULTS')
    expect(source).toContain('isVisionSimilarSearchTarget')
    expect(source).toContain('await this.readThumbnail(normalizedRequest.thumbnailPath)')
    expect(source).toContain("baseTokenizer: 'ngram'")
    expect(source).toContain('fullTextSearch(query')
    expect(source).toContain('isVideoSourceUnchanged')
    expect(source).toContain('refreshCaptions')
    expect(source).toContain("distanceType(VISION_VECTOR_DISTANCE_TYPE)")
    expect(source).toContain('Index.ivfFlat')
    expect(source).toContain('maintainVectorIndex')
    expect(source).toContain("stage: 'planning'")
    expect(source).toContain("stage: 'loading-model'")
    expect(source).toContain("stage: 'frames'")
    expect(source).toContain("stage: 'vector-index'")
    expect(source).toContain("stage: 'text-index'")
    expect(source).toContain("stage: 'scene-evidence'")
    expect(source).toContain("stage: 'entity-evidence'")
    expect(source).toContain("stage: 'completed'")
    expect(source).toContain('prepareImageModel')
    expect(source).toContain('getEntityLabels')
    expect(source).toContain('objectDetectionModelDirectory')
    expect(source).toContain('refreshObjectEvidence')
    expect(source).toContain("stage: 'object-evidence'")
    expect(source).toContain('this.objectDetection.prepare()')
    expect(source).toContain('getTextEmbedding(label.query)')
    expect(source).toContain('entityLabelEmbeddingsKey')
    expect(source).toContain('getTimings')
    expect(source).toContain("mode: VisionSearchMode = 'hybrid'")
  })

  it('keeps the indexed library browse surface wired to source thumbnails', () => {
    const panel = readFileSync(join(projectRoot, 'src/renderer/src/app/vision-panel.tsx'), 'utf8')
    const sources = readFileSync(join(projectRoot, 'src/renderer/src/app/vision-library-sources.tsx'), 'utf8')
    const styles = readFileSync(join(projectRoot, 'src/renderer/src/styles/player/vision-library-results.css'), 'utf8')
    const ipc = readFileSync(join(projectRoot, 'src/desktop/ipc-vision.ts'), 'utf8')
    const preload = readFileSync(join(projectRoot, 'src/preload/index.ts'), 'utf8')
    expect(panel).toContain('VisionLibrarySources')
    expect(panel).toContain('listVisionSources')
    expect(panel).toContain('openSource')
    expect(panel).toContain('readVisionThumbnail')
    expect(sources).toContain('onOpenSource')
    expect(sources).toContain('libraryFavorite')
    expect(sources).toContain('libraryProject')
    expect(sources).toContain('hasMoreSources')
    expect(sources).toContain('onLoadMore')
    expect(sources).toContain('libraryLoadMore')
    expect(styles).toContain('grid-template-columns: repeat(auto-fit, minmax(min(230px, 100%), 1fr));')
    expect(styles).toContain('padding: 6px 10px 6px 6px;')
    expect(styles).toContain('.vision-library-source > svg')
    expect(ipc).toContain('VISION_LIST_SOURCES')
    expect(ipc).toContain('listVisionSourcesWithMetadata')
    expect(ipc).toContain('refreshSidecars')
    expect(ipc).toContain('mergeVisionLibrarySourceMetadata')
    expect(preload).toContain('listVisionSources')
    expect(panel).toContain('VISION_SOURCE_PAGE_SIZE')
    expect(panel).toContain('offset: sources.length')
    expect(panel).toContain('includeEntityEvidence')
    expect(panel).toContain('includeObjectEvidence')
    expect(panel).toContain('entityAnalyzing')
    expect(panel).toContain('objectAnalyzing')
  })

  it('keeps the import inbox batch orchestration wired end to end', () => {
    const ipc = readFileSync(join(projectRoot, 'src/desktop/ipc-media-import-inbox.ts'), 'utf8')
    const preload = readFileSync(join(projectRoot, 'src/preload/index.ts'), 'utf8')
    const hook = readFileSync(join(projectRoot, 'src/renderer/src/app/use-vision-import-inbox.ts'), 'utf8')
    const inbox = readFileSync(join(projectRoot, 'src/renderer/src/app/vision-import-inbox.tsx'), 'utf8')
    expect(ipc).toContain('MEDIA_IMPORT_INBOX_BATCH_TRANSITION')
    expect(ipc).toContain('transitionBatch')
    expect(ipc).toContain('getMediaImportInboxProcessor().enqueue')
    expect(preload).toContain('transitionMediaImportInboxBatch')
    expect(hook).toContain('batchQueue')
    expect(hook).toContain('batchRetry')
    expect(inbox).toContain('selectedItemIds')
    expect(inbox).toContain('inboxBatchIgnore')
    expect(inbox).toContain("runBatch('clear')")
    expect(inbox).toContain('inboxBatchClear')
    expect(ipc).toContain("request.action !== 'clear'")
  })
})
